apiVersion: v2
name: metrics
description: Production-oriented Helm chart for Metrics
appVersion: 0.2.8
version: 0.1.22
sources:
  - https://github.com/pluralsh/telemetry
type: application
kubeVersion: '>=1.25.0-0'
keywords:
  - telemetry
  - prometheus
  - metrics
home: https://github.com/pluralsh/telemetry
