apiVersion: v2
name: telemetry-operator
description: Kubernetes operator for managing Plural Telemetry resources
appVersion: 0.1.1
version: 0.1.6
sources:
  - https://github.com/pluralsh/telemetry
type: application
kubeVersion: '>=1.25.0-0'
keywords:
  - telemetry
  - operator
  - kubebuilder
home: https://github.com/pluralsh/telemetry
