apiVersion: v2
name: telemetry-operator
description: Kubernetes operator for managing Plural Telemetry resources
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.25.0-0"
keywords:
  - telemetry
  - operator
  - kubebuilder
home: https://github.com/pluralsh/telemetry
sources:
  - https://github.com/pluralsh/telemetry
