[package]
name = "plural-metrics-server"
description = "Production HTTP and gRPC server for Metrics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "plural_metrics_server"
path = "src/lib.rs"

[[bin]]
name = "plural-metrics-server"
path = "src/main.rs"

[features]
default = ["kubernetes"]
kubernetes = ["sharding/kubernetes", "dep:kube"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum = "0.8.9"
blake3.workspace = true
bytes.workspace = true
clap = { version = "4.6.7", features = ["derive"] }
common = { path = "../common" }
futures.workspace = true
http-body-util = "0.1.5"
kube = { workspace = true, optional = true }
metrics.workspace = true
opentelemetry-proto.workspace = true
plural-metrics = { path = "../metrics", features = ["remote-write", "otel"] }
prost.workspace = true
proto = { path = "../proto" }
reqwest.workspace = true
serde.workspace = true
serde_html_form = "0.4.1"
serde_json.workspace = true
serde_urlencoded = "0.7.1"
serde_yaml.workspace = true
sharding = { path = "../sharding" }
server-common = { path = "../server-common" }
slatedb.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber = "0.3.23"
utoipa = { version = "6.0.0", features = ["axum_extras"] }

[dev-dependencies]
base64 = "0.23.1"
flate2 = "1"
tempfile.workspace = true
tower = { version = "0.5", features = ["util"] }
