{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "telemetry-operator.fullname" . }}
  labels:
    {{- include "telemetry-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["telemetry.plural.sh"]
    resources: ["meters", "lines", "tracks", "pseudofs", "namespaceauthentications"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["telemetry.plural.sh"]
    resources: ["meters/status", "lines/status", "tracks/status", "pseudofs/status", "namespaceauthentications/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["telemetry.plural.sh"]
    resources: ["meters/finalizers", "lines/finalizers", "tracks/finalizers", "pseudofs/finalizers", "namespaceauthentications/finalizers"]
    verbs: ["update"]
  - apiGroups: ["telemetry.plural.sh"]
    resources: ["shardmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets", "services", "serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}
