// Copyright 2026 Plural, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");

use super::ast::{
    BinaryModifier, BinaryOp, ComparisonOp, Conversion, Expr, FilterValue, FormatAssignment,
    FormatTemplate, FormatValue, GroupSide, Grouping, LabelFilterExpr, LabelPredicate,
    LabelSelection, LineFilter, LineFilterBranch, LineFilterOp, LineFilterTerm, LogExpr, MatchOp,
    Matcher, ParserExpression, ParserStage, PipelineStage, Query, RangeOp, Selector, Span, Spanned,
    TemplateSyntax, Unwrap, VectorMatching, VectorOp,
};
use super::error::ParseError;
use super::lexer::{Lexeme, Token, decode_string, lex};

// Generated by LALRPOP from grammar.lalrpop.
use super::grammar;

/// Templates compile with the query, so a bad template is a parse error
/// spanning its string literal.
fn compile_template(syntax: TemplateSyntax, token: &Lexeme) -> Result<FormatTemplate, ParseError> {
    FormatTemplate::new(syntax, decode_string(token)?)
        .map_err(|message| ParseError::new(message, token.span))
}

pub(crate) fn parse_syntax(source: &str) -> Result<Query, ParseError> {
    let tokens = lex(source)?;
    if tokens.is_empty() {
        return Err(ParseError::new("query cannot be empty", Span::new(0, 0)));
    }
    let mut parser = Parser {
        source,
        tokens,
        position: 0,
    };
    let query = parser.parse_expr()?;
    if let Some(token) = parser.peek() {
        return Err(ParseError::new(
            format!("unexpected token `{}`", token.text),
            token.span,
        ));
    }
    Ok(query)
}

#[derive(Clone, Debug)]
pub(crate) enum ExprToken {
    Operand(Query),
    Or((Option<BinaryModifier>, Span)),
    And((Option<BinaryModifier>, Span)),
    Unless((Option<BinaryModifier>, Span)),
    Equal((Option<BinaryModifier>, Span)),
    NotEqual((Option<BinaryModifier>, Span)),
    Greater((Option<BinaryModifier>, Span)),
    GreaterEqual((Option<BinaryModifier>, Span)),
    Less((Option<BinaryModifier>, Span)),
    LessEqual((Option<BinaryModifier>, Span)),
    Plus((Option<BinaryModifier>, Span)),
    Minus((Option<BinaryModifier>, Span)),
    Star((Option<BinaryModifier>, Span)),
    Slash((Option<BinaryModifier>, Span)),
    Percent((Option<BinaryModifier>, Span)),
    Caret((Option<BinaryModifier>, Span)),
}

pub(crate) fn combine_binary(
    lhs: Query,
    (op, modifier, _operator_span): (BinaryOp, Option<BinaryModifier>, Span),
    rhs: Query,
) -> Query {
    let span = lhs.span.join(rhs.span);
    Spanned::new(
        Expr::Binary {
            lhs: Box::new(lhs),
            op,
            modifier,
            rhs: Box::new(rhs),
        },
        span,
    )
}

struct Parser<'a> {
    source: &'a str,
    tokens: Vec<Lexeme>,
    position: usize,
}

impl Parser<'_> {
    fn parse_expr(&mut self) -> Result<Query, ParseError> {
        let mut tokens = Vec::new();
        let first = self.parse_primary()?;
        let start = first.span.start;
        let mut end = first.span.end;
        tokens.push((start, ExprToken::Operand(first), end));
        while let Some(op) = self.peek_binary_op() {
            let operator_span = self.next().expect("peeked").span;
            let modifier = self.parse_binary_modifier()?;
            let operator = expr_operator_token(op, modifier, operator_span);
            tokens.push((operator_span.start, operator, operator_span.end));
            let rhs = self.parse_primary()?;
            let rhs_span = rhs.span;
            end = rhs_span.end;
            tokens.push((rhs_span.start, ExprToken::Operand(rhs), rhs_span.end));
        }
        grammar::ExprParser::new()
            .parse(tokens.into_iter().map(Ok))
            .map_err(|error| {
                ParseError::new(
                    format!("invalid binary expression: {error:?}"),
                    Span::new(start, end),
                )
            })
    }

    fn parse_primary(&mut self) -> Result<Query, ParseError> {
        let token = self
            .peek()
            .ok_or_else(|| self.eof_error("expected expression"))?
            .clone();
        match token.token {
            Token::LeftBrace => self.parse_log_expr().map(|log| {
                let span = log_span(&log);
                Spanned::new(Expr::Log(log), span)
            }),
            Token::Number => {
                self.next();
                let value = parse_number_literal(&token)?;
                Ok(Spanned::new(Expr::Number(value), token.span))
            }
            Token::Plus | Token::Minus if self.check_n_token(1, Token::Number) => {
                let negative = token.token == Token::Minus;
                let start = self.next().expect("peeked").span;
                let number = self.expect_token(Token::Number, "expected number")?;
                let value = parse_number_literal(&number)?;
                Ok(Spanned::new(
                    Expr::Number(if negative { -value } else { value }),
                    start.join(number.span),
                ))
            }
            Token::LeftParen => {
                let start = self.next().expect("peeked").span;
                let mut expr = self.parse_expr()?;
                let end = self.expect_token(Token::RightParen, "expected `)`")?.span;
                expr.span = start.join(end);
                Ok(expr)
            }
            Token::Ident => self.parse_function_or_aggregation(),
            _ => Err(ParseError::new("expected expression", token.span)),
        }
    }

    fn parse_function_or_aggregation(&mut self) -> Result<Query, ParseError> {
        let name = self.next().expect("peeked").clone();
        let normalized_name = name.text.to_ascii_lowercase();
        if normalized_name == "vector" {
            self.expect_token(Token::LeftParen, "expected `(` after vector")?;
            let value = self.parse_signed_number()?;
            let end = self.expect_token(Token::RightParen, "expected `)` after vector")?;
            return Ok(Spanned::new(
                Expr::Vector(Box::new(Spanned::new(
                    Expr::Number(value),
                    name.span.join(end.span),
                ))),
                name.span.join(end.span),
            ));
        }
        if normalized_name == "label_replace" {
            return self.parse_label_replace(name.span);
        }
        if normalized_name == "approx_count_distinct" {
            return self.parse_label_aggregation(name.span);
        }
        if let Some(op) = range_op(&normalized_name) {
            return self.parse_range_aggregation(name.span, op);
        }
        if let Some(op) = vector_op(&normalized_name) {
            return self.parse_vector_aggregation(name.span, op);
        }
        Err(ParseError::new(
            format!("unknown function or aggregation `{}`", name.text),
            name.span,
        ))
    }

    fn parse_label_aggregation(&mut self, start: Span) -> Result<Query, ParseError> {
        self.expect_token(Token::LeftParen, "expected `(` after approx_count_distinct")?;
        let field = self.expect_ident("expected field name")?.text;
        self.expect_comma()?;
        let expr = self.parse_log_expr()?;
        if expr.range.is_none() {
            return Err(ParseError::new(
                "approx_count_distinct requires a range selector",
                log_span(&expr),
            ));
        }
        let end = self.expect_token(
            Token::RightParen,
            "expected `)` after approx_count_distinct",
        )?;
        let grouping = self.parse_optional_grouping()?;
        Ok(Spanned::new(
            Expr::LabelAggregation {
                field,
                expr,
                grouping,
            },
            start.join(end.span),
        ))
    }

    fn parse_label_replace(&mut self, start: Span) -> Result<Query, ParseError> {
        self.expect_token(Token::LeftParen, "expected `(` after label_replace")?;
        let expr = self.parse_expr()?;
        self.expect_comma()?;
        let dst = self.parse_string()?;
        self.expect_comma()?;
        let replacement = self.parse_string()?;
        self.expect_comma()?;
        let src = self.parse_string()?;
        self.expect_comma()?;
        let regex = self.parse_string()?;
        let end = self.expect_token(Token::RightParen, "expected `)` after label_replace")?;
        Ok(Spanned::new(
            Expr::LabelReplace {
                expr: Box::new(expr),
                dst,
                replacement,
                src,
                regex,
            },
            start.join(end.span),
        ))
    }

    fn parse_range_aggregation(&mut self, start: Span, op: RangeOp) -> Result<Query, ParseError> {
        self.expect_token(Token::LeftParen, "expected `(` after range aggregation")?;
        let parameter = if op == RangeOp::Quantile {
            if let Some(sign) = self.eat_token(Token::Minus) {
                return Err(ParseError::new("unexpected -", sign.span));
            }
            let number = self.parse_signed_number()?;
            self.expect_comma()?;
            Some(number)
        } else {
            None
        };
        let expr = self.parse_log_expr()?;
        if expr.range.is_none() {
            return Err(ParseError::new(
                "range aggregation requires a range selector",
                log_span(&expr),
            ));
        }
        let end = self.expect_token(Token::RightParen, "expected `)` after range aggregation")?;
        let grouping = self.parse_optional_grouping()?;
        Ok(Spanned::new(
            Expr::RangeAggregation {
                op,
                parameter,
                expr,
                grouping,
            },
            start.join(end.span),
        ))
    }

    fn parse_vector_aggregation(&mut self, start: Span, op: VectorOp) -> Result<Query, ParseError> {
        let leading_grouping = self.parse_optional_grouping()?;
        self.expect_token(Token::LeftParen, "expected `(` after aggregation")?;
        let parameter = if matches!(
            op,
            VectorOp::TopK | VectorOp::BottomK | VectorOp::ApproxTopK
        ) {
            let number = self.parse_signed_number()?;
            self.expect_comma()?;
            Some(number)
        } else {
            None
        };
        let expr = self.parse_expr()?;
        let end = self.expect_token(Token::RightParen, "expected `)` after aggregation")?;
        let trailing_grouping = self.parse_optional_grouping()?;
        if leading_grouping.is_some() && trailing_grouping.is_some() {
            return Err(ParseError::new(
                "aggregation can only have one grouping",
                end.span,
            ));
        }
        Ok(Spanned::new(
            Expr::VectorAggregation {
                op,
                parameter,
                expr: Box::new(expr),
                grouping: leading_grouping.or(trailing_grouping),
            },
            start.join(end.span),
        ))
    }

    fn parse_log_expr(&mut self) -> Result<LogExpr, ParseError> {
        let parenthesized = self.eat_token(Token::LeftParen).is_some();
        let selector = self.parse_selector()?;
        let mut stages = Vec::new();
        while self.starts_pipeline_stage() {
            stages.push(self.parse_pipeline_stage()?);
        }
        let closed_before_range = parenthesized && self.eat_token(Token::RightParen).is_some();
        let range = if self.eat_token(Token::LeftBracket).is_some() {
            let value = self.expect_quantity("expected duration in range selector")?;
            let end = self.expect_token(Token::RightBracket, "expected `]`")?;
            Some(Spanned::new(value.text, value.span.join(end.span)))
        } else {
            None
        };
        let offset = if self.eat_keyword("offset").is_some() {
            let value = self.expect_quantity("expected duration after offset")?;
            Some(Spanned::new(value.text, value.span))
        } else {
            None
        };
        while self.starts_pipeline_stage() {
            stages.push(self.parse_pipeline_stage()?);
        }
        if parenthesized && !closed_before_range {
            self.expect_token(Token::RightParen, "expected `)` after log range expression")?;
        }
        Ok(LogExpr {
            selector,
            stages,
            range,
            offset,
        })
    }

    fn parse_selector(&mut self) -> Result<Spanned<Selector>, ParseError> {
        let start = self
            .expect_token(Token::LeftBrace, "expected stream selector")?
            .span;
        let mut matchers = Vec::new();
        if !self.check_token(Token::RightBrace) {
            loop {
                let label = self.expect_ident("expected label name")?;
                let op_token = self.next_owned("expected matcher operator")?;
                let op = match op_token.token {
                    Token::Equal => MatchOp::Equal,
                    Token::NotEqual => MatchOp::NotEqual,
                    Token::RegexEqual => MatchOp::Regex,
                    Token::NotRegex => MatchOp::NotRegex,
                    _ => return Err(ParseError::new("expected matcher operator", op_token.span)),
                };
                let value_token = self.expect_string_token("expected matcher string")?;
                let value = decode_string(&value_token)?;
                matchers.push(Spanned::new(
                    Matcher {
                        label: label.text,
                        op,
                        value,
                    },
                    label.span.join(value_token.span),
                ));
                if self.eat_token(Token::Comma).is_none() {
                    break;
                }
            }
        }
        let end = self.expect_token(Token::RightBrace, "expected `}`")?.span;
        Ok(Spanned::new(Selector { matchers }, start.join(end)))
    }

    fn parse_pipeline_stage(&mut self) -> Result<Spanned<PipelineStage>, ParseError> {
        let start = self.peek().expect("pipeline checked").span;
        let value = match self.peek().expect("pipeline checked").token {
            Token::PipeEqual
            | Token::PipeRegex
            | Token::PipePattern
            | Token::NotEqual
            | Token::NotRegex
            | Token::NotPattern => PipelineStage::LineFilter(self.parse_line_filter()?),
            Token::Pipe
                if self.tokens.get(self.position + 1).map(|token| &token.token)
                    == Some(&Token::LeftParen) =>
            {
                self.next();
                PipelineStage::LabelFilter(self.parse_label_filter(0)?)
            }
            Token::Pipe => {
                self.next();
                let keyword = self.expect_ident("expected pipeline stage")?;
                match keyword.text.to_ascii_lowercase().as_str() {
                    "json" => PipelineStage::Parser(ParserStage::Json {
                        expressions: self.parse_parser_expressions()?,
                    }),
                    "logfmt" => PipelineStage::Parser(self.parse_logfmt()?),
                    "regexp" => PipelineStage::Parser(ParserStage::Regexp(self.parse_string()?)),
                    "pattern" => PipelineStage::Parser(ParserStage::Pattern(self.parse_string()?)),
                    "unpack" => PipelineStage::Parser(ParserStage::Unpack),
                    "line_format" => {
                        let syntax = self.parse_template_syntax(false);
                        PipelineStage::LineFormat(self.parse_template(syntax)?)
                    }
                    "label_format" => {
                        let syntax = self.parse_template_syntax(true);
                        PipelineStage::LabelFormat(self.parse_format_assignments(syntax)?)
                    }
                    "drop" => PipelineStage::Drop(self.parse_label_selections()?),
                    "keep" => PipelineStage::Keep(self.parse_label_selections()?),
                    "decolorize" => PipelineStage::Decolorize,
                    "unwrap" => PipelineStage::Unwrap(self.parse_unwrap()?),
                    "match" => PipelineStage::Match(self.parse_string()?),
                    _ => {
                        self.position -= 1;
                        PipelineStage::LabelFilter(self.parse_label_filter(0)?)
                    }
                }
            }
            _ => unreachable!("pipeline start checked"),
        };
        let end = self.previous_span();
        Ok(Spanned::new(value, start.join(end)))
    }

    fn parse_line_filter(&mut self) -> Result<LineFilter, ParseError> {
        let op_token = self.next().expect("line filter checked");
        let op = match op_token.token {
            Token::PipeEqual => LineFilterOp::Contains,
            Token::PipeRegex => LineFilterOp::Regex,
            Token::PipePattern => LineFilterOp::Pattern,
            Token::NotEqual => LineFilterOp::NotContains,
            Token::NotRegex => LineFilterOp::NotRegex,
            Token::NotPattern => LineFilterOp::NotPattern,
            _ => unreachable!("line filter checked"),
        };
        let mut branches = vec![LineFilterBranch {
            op,
            term: self.parse_line_filter_term()?,
        }];
        while self.eat_keyword("or").is_some() {
            branches.push(LineFilterBranch {
                op,
                term: self.parse_line_filter_term()?,
            });
        }
        Ok(LineFilter { branches })
    }

    fn parse_line_filter_term(&mut self) -> Result<LineFilterTerm, ParseError> {
        if self.eat_keyword("ip").is_some() {
            self.expect_token(Token::LeftParen, "expected `(` after ip")?;
            let value = self.parse_string()?;
            self.expect_token(Token::RightParen, "expected `)` after ip")?;
            Ok(LineFilterTerm::Ip(value))
        } else {
            self.parse_string().map(LineFilterTerm::String)
        }
    }

    fn parse_parser_expressions(&mut self) -> Result<Vec<ParserExpression>, ParseError> {
        let mut expressions = Vec::new();
        while self.check_token(Token::Ident) {
            let label = self.next().expect("checked").text.clone();
            let expression = if self.eat_token(Token::Equal).is_some() {
                self.parse_string()?
            } else {
                label.clone()
            };
            expressions.push(ParserExpression { label, expression });
            if self.eat_token(Token::Comma).is_none() {
                break;
            }
        }
        Ok(expressions)
    }

    fn parse_logfmt(&mut self) -> Result<ParserStage, ParseError> {
        let mut strict = false;
        let mut keep_empty = false;
        while let Some(flag) = self.peek().filter(|token| token.token == Token::Flag) {
            match flag.text.as_str() {
                "--strict" if !strict => strict = true,
                "--keep-empty" if !keep_empty => keep_empty = true,
                "--strict" | "--keep-empty" => {
                    return Err(ParseError::new("duplicate logfmt flag", flag.span));
                }
                _ => return Err(ParseError::new("unknown logfmt flag", flag.span)),
            }
            self.next();
        }
        let expressions = self.parse_parser_expressions()?;
        Ok(ParserStage::Logfmt {
            strict,
            keep_empty,
            expressions,
        })
    }

    /// The optional `jinja` keyword after `line_format` / `label_format`. In
    /// `label_format` it is a destination label when `=` follows.
    fn parse_template_syntax(&mut self, assignments: bool) -> TemplateSyntax {
        let keyword = self.peek().is_some_and(|token| {
            token.token == Token::Ident && token.text.eq_ignore_ascii_case("jinja")
        }) && !(assignments && self.check_n_token(1, Token::Equal));
        if keyword {
            self.next();
            TemplateSyntax::Jinja
        } else {
            TemplateSyntax::Go
        }
    }

    fn parse_template(&mut self, syntax: TemplateSyntax) -> Result<FormatTemplate, ParseError> {
        let token = self.expect_string_token("expected template string")?;
        compile_template(syntax, &token)
    }

    fn parse_format_assignments(
        &mut self,
        syntax: TemplateSyntax,
    ) -> Result<Vec<FormatAssignment>, ParseError> {
        let mut assignments = Vec::new();
        loop {
            let label = self.expect_ident("expected destination label")?;
            self.expect_token(Token::Equal, "expected `=`")?;
            let value = self.next_owned("expected format expression")?;
            let value = match value.token {
                Token::Quoted | Token::RawString => {
                    FormatValue::Template(compile_template(syntax, &value)?)
                }
                Token::Ident => FormatValue::Rename(value.text),
                _ => return Err(ParseError::new("expected label or template", value.span)),
            };
            assignments.push(FormatAssignment {
                label: label.text,
                value,
            });
            if self.eat_token(Token::Comma).is_none() {
                break;
            }
        }
        Ok(assignments)
    }

    fn parse_label_selections(&mut self) -> Result<Vec<LabelSelection>, ParseError> {
        let mut labels = Vec::new();
        loop {
            let label = self.expect_ident("expected label name")?;
            let matcher = if let Some(op) = self.peek_match_op() {
                self.next();
                Some((op, self.parse_string()?))
            } else {
                None
            };
            labels.push(LabelSelection {
                label: label.text,
                matcher,
            });
            if self.eat_token(Token::Comma).is_none() {
                break;
            }
        }
        Ok(labels)
    }

    fn parse_unwrap(&mut self) -> Result<Unwrap, ParseError> {
        let first = self.expect_ident("expected label or conversion after unwrap")?;
        let (conversion, label) = if self.eat_token(Token::LeftParen).is_some() {
            let conversion = match first.text.to_ascii_lowercase().as_str() {
                "bytes" => Conversion::Bytes,
                "duration" => Conversion::Duration,
                "duration_seconds" => Conversion::DurationSeconds,
                _ => return Err(ParseError::new("unknown unwrap conversion", first.span)),
            };
            let label = self.expect_ident("expected label in conversion")?.text;
            self.expect_token(Token::RightParen, "expected `)` after conversion")?;
            (Some(conversion), label)
        } else {
            (None, first.text)
        };
        let post_filter = if self.check_token(Token::Pipe) && self.pipeline_is_label_filter() {
            self.next();
            Some(Box::new(self.parse_label_filter(0)?))
        } else {
            None
        };
        Ok(Unwrap {
            conversion,
            label,
            post_filter,
        })
    }

    fn parse_label_filter(
        &mut self,
        minimum_precedence: u8,
    ) -> Result<Spanned<LabelFilterExpr>, ParseError> {
        let mut lhs = if self.eat_token(Token::LeftParen).is_some() {
            let mut expr = self.parse_label_filter(0)?;
            let end = self.expect_token(Token::RightParen, "expected `)` in label filter")?;
            expr.span.end = end.span.end;
            expr
        } else {
            self.parse_label_predicate()?
        };
        loop {
            let (is_and, precedence, consume_operator) =
                if self.check_keyword("and") || self.check_token(Token::Comma) {
                    (true, 2, true)
                } else if self.check_keyword("or") {
                    (false, 1, true)
                } else if self.starts_label_filter_atom() {
                    (true, 2, false)
                } else {
                    break;
                };
            if precedence < minimum_precedence {
                break;
            }
            if consume_operator {
                self.next();
            }
            let rhs = self.parse_label_filter(precedence + 1)?;
            let span = lhs.span.join(rhs.span);
            lhs = Spanned::new(
                if is_and {
                    LabelFilterExpr::And(Box::new(lhs), Box::new(rhs))
                } else {
                    LabelFilterExpr::Or(Box::new(lhs), Box::new(rhs))
                },
                span,
            );
        }
        Ok(lhs)
    }

    fn parse_label_predicate(&mut self) -> Result<Spanned<LabelFilterExpr>, ParseError> {
        let label = self.expect_ident("expected label in filter")?;
        let op_token = self.next_owned("expected comparison operator")?;
        let op = match op_token.token {
            Token::Equal | Token::EqualEqual => ComparisonOp::Equal,
            Token::NotEqual => ComparisonOp::NotEqual,
            Token::RegexEqual => ComparisonOp::Regex,
            Token::NotRegex => ComparisonOp::NotRegex,
            Token::Greater => ComparisonOp::Greater,
            Token::GreaterEqual => ComparisonOp::GreaterOrEqual,
            Token::Less => ComparisonOp::Less,
            Token::LessEqual => ComparisonOp::LessOrEqual,
            _ => {
                return Err(ParseError::new(
                    "expected comparison operator",
                    op_token.span,
                ));
            }
        };
        let sign = if self.eat_token(Token::Minus).is_some() {
            Some("-")
        } else if self.eat_token(Token::Plus).is_some() {
            Some("+")
        } else {
            None
        };
        let value_token = self.next_owned("expected filter value")?;
        let value = match value_token.token {
            Token::Quoted | Token::RawString if op_token.token == Token::EqualEqual => {
                return Err(ParseError::new(
                    "`==` compares numbers; use `=` for strings",
                    op_token.span,
                ));
            }
            Token::Quoted | Token::RawString => FilterValue::String(decode_string(&value_token)?),
            Token::Number => {
                let mut value = sign.unwrap_or_default().to_owned();
                value.push_str(&value_token.text);
                parse_number_text(&value, value_token.span)?;
                FilterValue::Number(value)
            }
            Token::Quantity => classify_quantity(value_token.text.clone()),
            Token::Ident if value_token.text == "ip" && self.check_token(Token::LeftParen) => {
                if !matches!(op_token.token, Token::Equal | Token::NotEqual) {
                    return Err(ParseError::new(
                        "ip() filters support only `=` and `!=`",
                        op_token.span,
                    ));
                }
                self.next();
                let ip = self.parse_string()?;
                let end = self.expect_token(Token::RightParen, "expected `)` after ip")?;
                let span = label.span.join(end.span);
                return Ok(Spanned::new(
                    LabelFilterExpr::Predicate(LabelPredicate {
                        label: label.text,
                        op,
                        value: FilterValue::Ip(ip),
                    }),
                    span,
                ));
            }
            Token::Ident => FilterValue::Identifier(value_token.text.clone()),
            _ => return Err(ParseError::new("expected filter value", value_token.span)),
        };
        if sign.is_some() && !matches!(value, FilterValue::Number(_)) {
            return Err(ParseError::new(
                "sign is only valid on numeric filter values",
                value_token.span,
            ));
        }
        Ok(Spanned::new(
            LabelFilterExpr::Predicate(LabelPredicate {
                label: label.text,
                op,
                value,
            }),
            label.span.join(value_token.span),
        ))
    }

    fn parse_binary_modifier(&mut self) -> Result<Option<BinaryModifier>, ParseError> {
        let return_bool = self.eat_keyword("bool").is_some();
        let matching = if self.check_keyword("on") || self.check_keyword("ignoring") {
            let on = self
                .next()
                .expect("checked")
                .text
                .eq_ignore_ascii_case("on");
            let labels = self.parse_label_list()?;
            let grouping = if self.check_keyword("group_left") || self.check_keyword("group_right")
            {
                let left = self
                    .next()
                    .expect("checked")
                    .text
                    .eq_ignore_ascii_case("group_left");
                let include = if self.check_token(Token::LeftParen) {
                    self.parse_label_list()?
                } else {
                    Vec::new()
                };
                Some(GroupSide { left, include })
            } else {
                None
            };
            Some(VectorMatching {
                on,
                labels,
                grouping,
            })
        } else {
            None
        };
        Ok(
            (return_bool || matching.is_some()).then_some(BinaryModifier {
                return_bool,
                matching,
            }),
        )
    }

    fn parse_optional_grouping(&mut self) -> Result<Option<Grouping>, ParseError> {
        if !self.check_keyword("by") && !self.check_keyword("without") {
            return Ok(None);
        }
        let without = self
            .next()
            .expect("checked")
            .text
            .eq_ignore_ascii_case("without");
        Ok(Some(Grouping {
            without,
            labels: self.parse_label_list()?,
        }))
    }

    fn parse_label_list(&mut self) -> Result<Vec<String>, ParseError> {
        self.expect_token(Token::LeftParen, "expected `(` before label list")?;
        let mut labels = Vec::new();
        if !self.check_token(Token::RightParen) {
            loop {
                labels.push(self.expect_ident("expected label name")?.text);
                if self.eat_token(Token::Comma).is_none() {
                    break;
                }
            }
        }
        self.expect_token(Token::RightParen, "expected `)` after label list")?;
        Ok(labels)
    }

    fn parse_signed_number(&mut self) -> Result<f64, ParseError> {
        let negative = self.eat_token(Token::Minus).is_some();
        let _positive = !negative && self.eat_token(Token::Plus).is_some();
        let token = self.expect_token(Token::Number, "expected number")?;
        let value = parse_number_literal(&token)?;
        Ok(if negative { -value } else { value })
    }

    fn starts_pipeline_stage(&self) -> bool {
        match self.peek().map(|token| &token.token) {
            Some(Token::Pipe | Token::PipeEqual | Token::PipeRegex | Token::PipePattern) => true,
            Some(Token::NotEqual | Token::NotRegex | Token::NotPattern) => {
                self.tokens.get(self.position + 1).is_some_and(|token| {
                    matches!(token.token, Token::Quoted | Token::RawString)
                        || (token.token == Token::Ident && token.text.eq_ignore_ascii_case("ip"))
                })
            }
            _ => false,
        }
    }

    fn pipeline_is_label_filter(&self) -> bool {
        self.tokens.get(self.position + 1).is_some_and(|token| {
            token.token == Token::LeftParen
                || (token.token == Token::Ident && !is_named_stage(&token.text))
        })
    }

    fn starts_label_filter_atom(&self) -> bool {
        self.check_token(Token::LeftParen)
            || (self.check_token(Token::Ident)
                && self.tokens.get(self.position + 1).is_some_and(|token| {
                    matches!(
                        token.token,
                        Token::Equal
                            | Token::EqualEqual
                            | Token::NotEqual
                            | Token::RegexEqual
                            | Token::NotRegex
                            | Token::Greater
                            | Token::GreaterEqual
                            | Token::Less
                            | Token::LessEqual
                    )
                }))
    }

    fn peek_binary_op(&self) -> Option<BinaryOp> {
        let token = self.peek()?;
        match token.token {
            Token::Plus => Some(BinaryOp::Add),
            Token::Minus => Some(BinaryOp::Sub),
            Token::Star => Some(BinaryOp::Mul),
            Token::Slash => Some(BinaryOp::Div),
            Token::Percent => Some(BinaryOp::Mod),
            Token::Caret => Some(BinaryOp::Pow),
            Token::EqualEqual => Some(BinaryOp::Equal),
            Token::NotEqual => Some(BinaryOp::NotEqual),
            Token::Greater => Some(BinaryOp::Greater),
            Token::GreaterEqual => Some(BinaryOp::GreaterOrEqual),
            Token::Less => Some(BinaryOp::Less),
            Token::LessEqual => Some(BinaryOp::LessOrEqual),
            Token::Ident if token.text.eq_ignore_ascii_case("and") => Some(BinaryOp::And),
            Token::Ident if token.text.eq_ignore_ascii_case("or") => Some(BinaryOp::Or),
            Token::Ident if token.text.eq_ignore_ascii_case("unless") => Some(BinaryOp::Unless),
            _ => None,
        }
    }

    fn peek_match_op(&self) -> Option<MatchOp> {
        match self.peek()?.token {
            Token::Equal => Some(MatchOp::Equal),
            Token::NotEqual => Some(MatchOp::NotEqual),
            Token::RegexEqual => Some(MatchOp::Regex),
            Token::NotRegex => Some(MatchOp::NotRegex),
            _ => None,
        }
    }

    fn expect_quantity(&mut self, message: &str) -> Result<Lexeme, ParseError> {
        let token = self.next_owned(message)?;
        if matches!(token.token, Token::Quantity | Token::Ident) {
            Ok(token)
        } else {
            Err(ParseError::new(message, token.span))
        }
    }

    fn parse_string(&mut self) -> Result<String, ParseError> {
        let token = self.expect_string_token("expected string")?;
        decode_string(&token)
    }

    fn expect_string_token(&mut self, message: &str) -> Result<Lexeme, ParseError> {
        let token = self.next_owned(message)?;
        if matches!(token.token, Token::Quoted | Token::RawString) {
            Ok(token)
        } else {
            Err(ParseError::new(message, token.span))
        }
    }

    fn expect_ident(&mut self, message: &str) -> Result<Lexeme, ParseError> {
        self.expect_token(Token::Ident, message)
    }

    fn expect_comma(&mut self) -> Result<(), ParseError> {
        self.expect_token(Token::Comma, "expected `,`")?;
        Ok(())
    }

    fn expect_token(&mut self, expected: Token, message: &str) -> Result<Lexeme, ParseError> {
        let token = self.next_owned(message)?;
        if token.token == expected {
            Ok(token)
        } else {
            Err(ParseError::new(message, token.span))
        }
    }

    fn eat_token(&mut self, expected: Token) -> Option<Lexeme> {
        if self.check_token(expected) {
            self.next().cloned()
        } else {
            None
        }
    }

    fn eat_keyword(&mut self, keyword: &str) -> Option<Lexeme> {
        if self.check_keyword(keyword) {
            self.next().cloned()
        } else {
            None
        }
    }

    fn check_token(&self, expected: Token) -> bool {
        self.peek().is_some_and(|token| token.token == expected)
    }

    fn check_n_token(&self, offset: usize, expected: Token) -> bool {
        self.tokens
            .get(self.position + offset)
            .is_some_and(|token| token.token == expected)
    }

    fn check_keyword(&self, keyword: &str) -> bool {
        self.peek().is_some_and(|token| {
            token.token == Token::Ident && token.text.eq_ignore_ascii_case(keyword)
        })
    }

    fn peek(&self) -> Option<&Lexeme> {
        self.tokens.get(self.position)
    }

    fn next(&mut self) -> Option<&Lexeme> {
        let token = self.tokens.get(self.position);
        if token.is_some() {
            self.position += 1;
        }
        token
    }

    fn next_owned(&mut self, message: &str) -> Result<Lexeme, ParseError> {
        if let Some(token) = self.tokens.get(self.position).cloned() {
            self.position += 1;
            Ok(token)
        } else {
            Err(self.eof_error(message))
        }
    }

    fn previous_span(&self) -> Span {
        self.tokens[self.position - 1].span
    }

    fn eof_error(&self, message: &str) -> ParseError {
        let position = self.source.len();
        ParseError::new(message, Span::new(position, position))
    }
}

fn classify_quantity(value: String) -> FilterValue {
    let lowercase = value.to_ascii_lowercase();
    if lowercase.ends_with('b') {
        FilterValue::Bytes(value)
    } else {
        FilterValue::Duration(value)
    }
}

fn parse_number_literal(token: &Lexeme) -> Result<f64, ParseError> {
    parse_number_text(&token.text, token.span)
}

fn parse_number_text(text: &str, span: Span) -> Result<f64, ParseError> {
    let normalized = text.replace('_', "");
    if normalized.trim_start_matches(['+', '-']).starts_with("0x")
        || normalized.trim_start_matches(['+', '-']).starts_with("0X")
    {
        parse_hex_float(&normalized)
            .ok_or_else(|| ParseError::new(format!("invalid hex float `{text}`"), span))
    } else {
        normalized
            .parse()
            .map_err(|_| ParseError::new(format!("invalid number `{text}`"), span))
    }
}

fn parse_hex_float(value: &str) -> Option<f64> {
    let (negative, unsigned) = if let Some(rest) = value.strip_prefix('-') {
        (true, rest)
    } else {
        (false, value.strip_prefix('+').unwrap_or(value))
    };
    let body = unsigned
        .strip_prefix("0x")
        .or_else(|| unsigned.strip_prefix("0X"))?;
    let exponent_at = body.find(['p', 'P'])?;
    let (mantissa, exponent) = body.split_at(exponent_at);
    let exponent: i32 = exponent[1..].parse().ok()?;
    let mut parts = mantissa.split('.');
    let integer = parts.next()?;
    let fraction = parts.next().unwrap_or("");
    if parts.next().is_some() {
        return None;
    }
    let integer = if integer.is_empty() {
        0.0
    } else {
        u64::from_str_radix(integer, 16).ok()? as f64
    };
    let mut fraction_value = 0.0;
    for (index, digit) in fraction.chars().enumerate() {
        fraction_value += f64::from(digit.to_digit(16)?) / 16_f64.powi(index as i32 + 1);
    }
    let result = (integer + fraction_value) * 2_f64.powi(exponent);
    Some(if negative { -result } else { result })
}

fn expr_operator_token(op: BinaryOp, modifier: Option<BinaryModifier>, span: Span) -> ExprToken {
    let value = (modifier, span);
    match op {
        BinaryOp::Or => ExprToken::Or(value),
        BinaryOp::And => ExprToken::And(value),
        BinaryOp::Unless => ExprToken::Unless(value),
        BinaryOp::Equal => ExprToken::Equal(value),
        BinaryOp::NotEqual => ExprToken::NotEqual(value),
        BinaryOp::Greater => ExprToken::Greater(value),
        BinaryOp::GreaterOrEqual => ExprToken::GreaterEqual(value),
        BinaryOp::Less => ExprToken::Less(value),
        BinaryOp::LessOrEqual => ExprToken::LessEqual(value),
        BinaryOp::Add => ExprToken::Plus(value),
        BinaryOp::Sub => ExprToken::Minus(value),
        BinaryOp::Mul => ExprToken::Star(value),
        BinaryOp::Div => ExprToken::Slash(value),
        BinaryOp::Mod => ExprToken::Percent(value),
        BinaryOp::Pow => ExprToken::Caret(value),
    }
}

fn log_span(log: &LogExpr) -> Span {
    let end = log
        .offset
        .as_ref()
        .or(log.range.as_ref())
        .map_or(log.selector.span.end, |value| value.span.end);
    Span::new(log.selector.span.start, end)
}

fn is_named_stage(name: &str) -> bool {
    matches!(
        name.to_ascii_lowercase().as_str(),
        "json"
            | "logfmt"
            | "regexp"
            | "pattern"
            | "unpack"
            | "line_format"
            | "label_format"
            | "drop"
            | "keep"
            | "decolorize"
            | "unwrap"
            | "match"
    )
}

fn range_op(name: &str) -> Option<RangeOp> {
    match name {
        "count_over_time" => Some(RangeOp::Count),
        "rate" => Some(RangeOp::Rate),
        "rate_counter" => Some(RangeOp::RateCounter),
        "bytes_over_time" => Some(RangeOp::Bytes),
        "bytes_rate" => Some(RangeOp::BytesRate),
        "avg_over_time" => Some(RangeOp::Avg),
        "sum_over_time" => Some(RangeOp::Sum),
        "min_over_time" => Some(RangeOp::Min),
        "max_over_time" => Some(RangeOp::Max),
        "stddev_over_time" => Some(RangeOp::Stddev),
        "stdvar_over_time" => Some(RangeOp::Stdvar),
        "quantile_over_time" => Some(RangeOp::Quantile),
        "first_over_time" => Some(RangeOp::First),
        "last_over_time" => Some(RangeOp::Last),
        "absent_over_time" => Some(RangeOp::Absent),
        _ => None,
    }
}

fn vector_op(name: &str) -> Option<VectorOp> {
    match name {
        "sum" => Some(VectorOp::Sum),
        "avg" => Some(VectorOp::Avg),
        "min" => Some(VectorOp::Min),
        "max" => Some(VectorOp::Max),
        "count" => Some(VectorOp::Count),
        "stddev" => Some(VectorOp::Stddev),
        "stdvar" => Some(VectorOp::Stdvar),
        "topk" => Some(VectorOp::TopK),
        "bottomk" => Some(VectorOp::BottomK),
        "sort" => Some(VectorOp::Sort),
        "sort_desc" => Some(VectorOp::SortDesc),
        "approx_topk" => Some(VectorOp::ApproxTopK),
        _ => None,
    }
}
