apiVersion: telemetry.plural.sh/v1alpha1
kind: Logs
metadata:
  name: logs-sample
spec:
  mode: Standalone
  version: 0.1.0
  image:
    repository: ghcr.io/pluralsh/logs
    pullPolicy: IfNotPresent
  config:
    auth:
      unauthenticated: false
    namespaces:
      - default
    storage:
      objectStore:
        type: Local
  ingress:
    enabled: false
  writer:
    # Standalone mode always runs exactly one replica.
    replicas: 1
    nodeSelector:
      kubernetes.io/os: linux
