apiVersion: telemetry.plural.sh/v1alpha1
kind: Traces
metadata:
  name: traces-sample
spec:
  mode: Sharded
  version: 0.1.0
  config:
    storage:
      path: traces
      objectStore:
        type: Local
        path: /var/lib/traces/data
    sharding:
      leaseDurationSeconds: 15
      renewIntervalSeconds: 5
    namespaces:
      - default
  writer:
    replicas: 3
    dataVolume:
      persistentVolumeClaim:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  reader:
    replicas: 2
