apiVersion: v2
name: telemetry-stack
description: Plural Telemetry metrics, logs, traces, and namespace authentication resources
appVersion: 0.2.7
version: 0.1.6
sources:
  - https://github.com/pluralsh/telemetry
type: application
kubeVersion: '>=1.25.0-0'
keywords:
  - telemetry
  - observability
  - metrics
  - logs
  - traces
home: https://github.com/pluralsh/telemetry
