//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSObjectStoreSpec) DeepCopyInto(out *AWSObjectStoreSpec) {
	*out = *in
	if in.AccessKeyIDSecretRef != nil {
		in, out := &in.AccessKeyIDSecretRef, &out.AccessKeyIDSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretAccessKeySecretRef != nil {
		in, out := &in.SecretAccessKeySecretRef, &out.SecretAccessKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SessionTokenSecretRef != nil {
		in, out := &in.SessionTokenSecretRef, &out.SessionTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSObjectStoreSpec.
func (in *AWSObjectStoreSpec) DeepCopy() *AWSObjectStoreSpec {
	if in == nil {
		return nil
	}
	out := new(AWSObjectStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessSpec) DeepCopyInto(out *AccessSpec) {
	*out = *in
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = make([]BasicCredentialSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Write != nil {
		in, out := &in.Write, &out.Write
		*out = make([]BasicCredentialSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessSpec.
func (in *AccessSpec) DeepCopy() *AccessSpec {
	if in == nil {
		return nil
	}
	out := new(AccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
	in.Global.DeepCopyInto(&out.Global)
	if in.JWT != nil {
		in, out := &in.JWT, &out.JWT
		*out = new(JWTSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.InternalTokenSecretRef != nil {
		in, out := &in.InternalTokenSecretRef, &out.InternalTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSpec.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClientSecretAuthSpec) DeepCopyInto(out *AzureClientSecretAuthSpec) {
	*out = *in
	in.ClientSecretKeyRef.DeepCopyInto(&out.ClientSecretKeyRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClientSecretAuthSpec.
func (in *AzureClientSecretAuthSpec) DeepCopy() *AzureClientSecretAuthSpec {
	if in == nil {
		return nil
	}
	out := new(AzureClientSecretAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureObjectStoreSpec) DeepCopyInto(out *AzureObjectStoreSpec) {
	*out = *in
	if in.AccessKeySecretRef != nil {
		in, out := &in.AccessKeySecretRef, &out.AccessKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SASTokenSecretRef != nil {
		in, out := &in.SASTokenSecretRef, &out.SASTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.BearerTokenSecretRef != nil {
		in, out := &in.BearerTokenSecretRef, &out.BearerTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(AzureClientSecretAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadIdentity != nil {
		in, out := &in.WorkloadIdentity, &out.WorkloadIdentity
		*out = new(AzureWorkloadIdentityAuthSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureObjectStoreSpec.
func (in *AzureObjectStoreSpec) DeepCopy() *AzureObjectStoreSpec {
	if in == nil {
		return nil
	}
	out := new(AzureObjectStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureWorkloadIdentityAuthSpec) DeepCopyInto(out *AzureWorkloadIdentityAuthSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureWorkloadIdentityAuthSpec.
func (in *AzureWorkloadIdentityAuthSpec) DeepCopy() *AzureWorkloadIdentityAuthSpec {
	if in == nil {
		return nil
	}
	out := new(AzureWorkloadIdentityAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicCredentialSpec) DeepCopyInto(out *BasicCredentialSpec) {
	*out = *in
	in.Password.DeepCopyInto(&out.Password)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicCredentialSpec.
func (in *BasicCredentialSpec) DeepCopy() *BasicCredentialSpec {
	if in == nil {
		return nil
	}
	out := new(BasicCredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheSpec) DeepCopyInto(out *CacheSpec) {
	*out = *in
	if in.MemoryCapacity != nil {
		in, out := &in.MemoryCapacity, &out.MemoryCapacity
		*out = new(int64)
		**out = **in
	}
	if in.DiskCapacity != nil {
		in, out := &in.DiskCapacity, &out.DiskCapacity
		*out = new(int64)
		**out = **in
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(int64)
		**out = **in
	}
	if in.Shards != nil {
		in, out := &in.Shards, &out.Shards
		*out = new(int32)
		**out = **in
	}
	if in.Flushers != nil {
		in, out := &in.Flushers, &out.Flushers
		*out = new(int32)
		**out = **in
	}
	if in.BufferPoolSize != nil {
		in, out := &in.BufferPoolSize, &out.BufferPoolSize
		*out = new(int64)
		**out = **in
	}
	if in.SubmitQueueSizeThreshold != nil {
		in, out := &in.SubmitQueueSizeThreshold, &out.SubmitQueueSizeThreshold
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheSpec.
func (in *CacheSpec) DeepCopy() *CacheSpec {
	if in == nil {
		return nil
	}
	out := new(CacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheWarmerSpec) DeepCopyInto(out *CacheWarmerSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.WarmRangeSeconds != nil {
		in, out := &in.WarmRangeSeconds, &out.WarmRangeSeconds
		*out = new(int64)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(int32)
		**out = **in
	}
	if in.IncludePayloads != nil {
		in, out := &in.IncludePayloads, &out.IncludePayloads
		*out = new(bool)
		**out = **in
	}
	if in.Continuous != nil {
		in, out := &in.Continuous, &out.Continuous
		*out = new(ContinuousCacheWarmerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheWarmerSpec.
func (in *CacheWarmerSpec) DeepCopy() *CacheWarmerSpec {
	if in == nil {
		return nil
	}
	out := new(CacheWarmerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousCacheWarmerSpec) DeepCopyInto(out *ContinuousCacheWarmerSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.IntervalSeconds != nil {
		in, out := &in.IntervalSeconds, &out.IntervalSeconds
		*out = new(int64)
		**out = **in
	}
	if in.WarmRangeSeconds != nil {
		in, out := &in.WarmRangeSeconds, &out.WarmRangeSeconds
		*out = new(int64)
		**out = **in
	}
	if in.IncludePayloads != nil {
		in, out := &in.IncludePayloads, &out.IncludePayloads
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousCacheWarmerSpec.
func (in *ContinuousCacheWarmerSpec) DeepCopy() *ContinuousCacheWarmerSpec {
	if in == nil {
		return nil
	}
	out := new(ContinuousCacheWarmerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataStoreReference) DeepCopyInto(out *DataStoreReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataStoreReference.
func (in *DataStoreReference) DeepCopy() *DataStoreReference {
	if in == nil {
		return nil
	}
	out := new(DataStoreReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPObjectStoreSpec) DeepCopyInto(out *GCPObjectStoreSpec) {
	*out = *in
	if in.ServiceAccountKeySecretRef != nil {
		in, out := &in.ServiceAccountKeySecretRef, &out.ServiceAccountKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.BearerTokenSecretRef != nil {
		in, out := &in.BearerTokenSecretRef, &out.BearerTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPObjectStoreSpec.
func (in *GCPObjectStoreSpec) DeepCopy() *GCPObjectStoreSpec {
	if in == nil {
		return nil
	}
	out := new(GCPObjectStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HashRange) DeepCopyInto(out *HashRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HashRange.
func (in *HashRange) DeepCopy() *HashRange {
	if in == nil {
		return nil
	}
	out := new(HashRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HashRangeAssignment) DeepCopyInto(out *HashRangeAssignment) {
	*out = *in
	out.Range = in.Range
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HashRangeAssignment.
func (in *HashRangeAssignment) DeepCopy() *HashRangeAssignment {
	if in == nil {
		return nil
	}
	out := new(HashRangeAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HashRangeMap) DeepCopyInto(out *HashRangeMap) {
	*out = *in
	if in.Assignments != nil {
		in, out := &in.Assignments, &out.Assignments
		*out = make([]HashRangeAssignment, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HashRangeMap.
func (in *HashRangeMap) DeepCopy() *HashRangeMap {
	if in == nil {
		return nil
	}
	out := new(HashRangeMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressMetadataSpec) DeepCopyInto(out *IngressMetadataSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressMetadataSpec.
func (in *IngressMetadataSpec) DeepCopy() *IngressMetadataSpec {
	if in == nil {
		return nil
	}
	out := new(IngressMetadataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressTLSSpec) DeepCopyInto(out *IngressTLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressTLSSpec.
func (in *IngressTLSSpec) DeepCopy() *IngressTLSSpec {
	if in == nil {
		return nil
	}
	out := new(IngressTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWKSSpec) DeepCopyInto(out *JWKSSpec) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWKSSpec.
func (in *JWKSSpec) DeepCopy() *JWKSSpec {
	if in == nil {
		return nil
	}
	out := new(JWKSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTSpec) DeepCopyInto(out *JWTSpec) {
	*out = *in
	in.JWKS.DeepCopyInto(&out.JWKS)
	if in.RefreshIntervalSeconds != nil {
		in, out := &in.RefreshIntervalSeconds, &out.RefreshIntervalSeconds
		*out = new(int64)
		**out = **in
	}
	if in.RequestTimeoutSeconds != nil {
		in, out := &in.RequestTimeoutSeconds, &out.RequestTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTSpec.
func (in *JWTSpec) DeepCopy() *JWTSpec {
	if in == nil {
		return nil
	}
	out := new(JWTSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Logs) DeepCopyInto(out *Logs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Logs.
func (in *Logs) DeepCopy() *Logs {
	if in == nil {
		return nil
	}
	out := new(Logs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Logs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsConfigSpec) DeepCopyInto(out *LogsConfigSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	if in.SegmentDurationSeconds != nil {
		in, out := &in.SegmentDurationSeconds, &out.SegmentDurationSeconds
		*out = new(int64)
		**out = **in
	}
	if in.RetentionSeconds != nil {
		in, out := &in.RetentionSeconds, &out.RetentionSeconds
		*out = new(int64)
		**out = **in
	}
	in.Page.DeepCopyInto(&out.Page)
	in.Write.DeepCopyInto(&out.Write)
	in.Sharding.DeepCopyInto(&out.Sharding)
	in.Request.DeepCopyInto(&out.Request)
	in.Elasticsearch.DeepCopyInto(&out.Elasticsearch)
	if in.CacheWarmer != nil {
		in, out := &in.CacheWarmer, &out.CacheWarmer
		*out = new(CacheWarmerSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Auth.DeepCopyInto(&out.Auth)
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsConfigSpec.
func (in *LogsConfigSpec) DeepCopy() *LogsConfigSpec {
	if in == nil {
		return nil
	}
	out := new(LogsConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsElasticsearchSpec) DeepCopyInto(out *LogsElasticsearchSpec) {
	*out = *in
	if in.MessageFields != nil {
		in, out := &in.MessageFields, &out.MessageFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StreamFields != nil {
		in, out := &in.StreamFields, &out.StreamFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsElasticsearchSpec.
func (in *LogsElasticsearchSpec) DeepCopy() *LogsElasticsearchSpec {
	if in == nil {
		return nil
	}
	out := new(LogsElasticsearchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsList) DeepCopyInto(out *LogsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Logs, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsList.
func (in *LogsList) DeepCopy() *LogsList {
	if in == nil {
		return nil
	}
	out := new(LogsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsPageSpec) DeepCopyInto(out *LogsPageSpec) {
	*out = *in
	if in.TargetSizeBytes != nil {
		in, out := &in.TargetSizeBytes, &out.TargetSizeBytes
		*out = new(int64)
		**out = **in
	}
	if in.MaxRows != nil {
		in, out := &in.MaxRows, &out.MaxRows
		*out = new(int64)
		**out = **in
	}
	if in.RowsPerBlock != nil {
		in, out := &in.RowsPerBlock, &out.RowsPerBlock
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsPageSpec.
func (in *LogsPageSpec) DeepCopy() *LogsPageSpec {
	if in == nil {
		return nil
	}
	out := new(LogsPageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsRequestSpec) DeepCopyInto(out *LogsRequestSpec) {
	*out = *in
	if in.MaxRequestBytes != nil {
		in, out := &in.MaxRequestBytes, &out.MaxRequestBytes
		*out = new(int64)
		**out = **in
	}
	if in.MaxDecodedRequestBytes != nil {
		in, out := &in.MaxDecodedRequestBytes, &out.MaxDecodedRequestBytes
		*out = new(int64)
		**out = **in
	}
	if in.MaxQueryEntries != nil {
		in, out := &in.MaxQueryEntries, &out.MaxQueryEntries
		*out = new(int64)
		**out = **in
	}
	if in.MaxQueryPages != nil {
		in, out := &in.MaxQueryPages, &out.MaxQueryPages
		*out = new(int64)
		**out = **in
	}
	if in.MaxStructuredMetadataFields != nil {
		in, out := &in.MaxStructuredMetadataFields, &out.MaxStructuredMetadataFields
		*out = new(int64)
		**out = **in
	}
	if in.QueryConcurrency != nil {
		in, out := &in.QueryConcurrency, &out.QueryConcurrency
		*out = new(int32)
		**out = **in
	}
	if in.MaxInFlightQueryBytes != nil {
		in, out := &in.MaxInFlightQueryBytes, &out.MaxInFlightQueryBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsRequestSpec.
func (in *LogsRequestSpec) DeepCopy() *LogsRequestSpec {
	if in == nil {
		return nil
	}
	out := new(LogsRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsSpec) DeepCopyInto(out *LogsSpec) {
	*out = *in
	out.Image = in.Image
	in.Config.DeepCopyInto(&out.Config)
	in.Writer.DeepCopyInto(&out.Writer)
	in.Reader.DeepCopyInto(&out.Reader)
	in.Service.DeepCopyInto(&out.Service)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsSpec.
func (in *LogsSpec) DeepCopy() *LogsSpec {
	if in == nil {
		return nil
	}
	out := new(LogsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsStatus) DeepCopyInto(out *LogsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.WriterScalingStatus.DeepCopyInto(&out.WriterScalingStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsStatus.
func (in *LogsStatus) DeepCopy() *LogsStatus {
	if in == nil {
		return nil
	}
	out := new(LogsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Metrics) DeepCopyInto(out *Metrics) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metrics.
func (in *Metrics) DeepCopy() *Metrics {
	if in == nil {
		return nil
	}
	out := new(Metrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Metrics) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsConfigSpec) DeepCopyInto(out *MetricsConfigSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	if in.ReaderCacheCapacity != nil {
		in, out := &in.ReaderCacheCapacity, &out.ReaderCacheCapacity
		*out = new(int64)
		**out = **in
	}
	if in.ForwardIndexCacheCapacityBytes != nil {
		in, out := &in.ForwardIndexCacheCapacityBytes, &out.ForwardIndexCacheCapacityBytes
		*out = new(int64)
		**out = **in
	}
	if in.CacheWarmer != nil {
		in, out := &in.CacheWarmer, &out.CacheWarmer
		*out = new(CacheWarmerSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Write.DeepCopyInto(&out.Write)
	in.Request.DeepCopyInto(&out.Request)
	in.Sharding.DeepCopyInto(&out.Sharding)
	in.Auth.DeepCopyInto(&out.Auth)
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsConfigSpec.
func (in *MetricsConfigSpec) DeepCopy() *MetricsConfigSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsList) DeepCopyInto(out *MetricsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Metrics, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsList.
func (in *MetricsList) DeepCopy() *MetricsList {
	if in == nil {
		return nil
	}
	out := new(MetricsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MetricsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsRequestSpec) DeepCopyInto(out *MetricsRequestSpec) {
	*out = *in
	if in.MaxRequestBytes != nil {
		in, out := &in.MaxRequestBytes, &out.MaxRequestBytes
		*out = new(int64)
		**out = **in
	}
	if in.MaxDecodedRequestBytes != nil {
		in, out := &in.MaxDecodedRequestBytes, &out.MaxDecodedRequestBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsRequestSpec.
func (in *MetricsRequestSpec) DeepCopy() *MetricsRequestSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSpec) DeepCopyInto(out *MetricsSpec) {
	*out = *in
	out.Image = in.Image
	in.Config.DeepCopyInto(&out.Config)
	in.Writer.DeepCopyInto(&out.Writer)
	in.Reader.DeepCopyInto(&out.Reader)
	in.Service.DeepCopyInto(&out.Service)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSpec.
func (in *MetricsSpec) DeepCopy() *MetricsSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsStatus) DeepCopyInto(out *MetricsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.WriterScalingStatus.DeepCopyInto(&out.WriterScalingStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsStatus.
func (in *MetricsStatus) DeepCopy() *MetricsStatus {
	if in == nil {
		return nil
	}
	out := new(MetricsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceAuthentication) DeepCopyInto(out *NamespaceAuthentication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceAuthentication.
func (in *NamespaceAuthentication) DeepCopy() *NamespaceAuthentication {
	if in == nil {
		return nil
	}
	out := new(NamespaceAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceAuthentication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceAuthenticationList) DeepCopyInto(out *NamespaceAuthenticationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NamespaceAuthentication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceAuthenticationList.
func (in *NamespaceAuthenticationList) DeepCopy() *NamespaceAuthenticationList {
	if in == nil {
		return nil
	}
	out := new(NamespaceAuthenticationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceAuthenticationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceAuthenticationSpec) DeepCopyInto(out *NamespaceAuthenticationSpec) {
	*out = *in
	out.DataStoreRef = in.DataStoreRef
	in.SecretKeyRef.DeepCopyInto(&out.SecretKeyRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceAuthenticationSpec.
func (in *NamespaceAuthenticationSpec) DeepCopy() *NamespaceAuthenticationSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceAuthenticationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceAuthenticationStatus) DeepCopyInto(out *NamespaceAuthenticationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceAuthenticationStatus.
func (in *NamespaceAuthenticationStatus) DeepCopy() *NamespaceAuthenticationStatus {
	if in == nil {
		return nil
	}
	out := new(NamespaceAuthenticationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreSpec) DeepCopyInto(out *ObjectStoreSpec) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSObjectStoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureObjectStoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(GCPObjectStoreSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreSpec.
func (in *ObjectStoreSpec) DeepCopy() *ObjectStoreSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeClaimRetentionPolicySpec) DeepCopyInto(out *PersistentVolumeClaimRetentionPolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeClaimRetentionPolicySpec.
func (in *PersistentVolumeClaimRetentionPolicySpec) DeepCopy() *PersistentVolumeClaimRetentionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeClaimRetentionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PseudoFS) DeepCopyInto(out *PseudoFS) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PseudoFS.
func (in *PseudoFS) DeepCopy() *PseudoFS {
	if in == nil {
		return nil
	}
	out := new(PseudoFS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PseudoFS) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PseudoFSConfigSpec) DeepCopyInto(out *PseudoFSConfigSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	if in.ChunkSizeBytes != nil {
		in, out := &in.ChunkSizeBytes, &out.ChunkSizeBytes
		*out = new(int64)
		**out = **in
	}
	if in.MaxFileSizeBytes != nil {
		in, out := &in.MaxFileSizeBytes, &out.MaxFileSizeBytes
		*out = new(int64)
		**out = **in
	}
	if in.MaxAppendGenerations != nil {
		in, out := &in.MaxAppendGenerations, &out.MaxAppendGenerations
		*out = new(int64)
		**out = **in
	}
	if in.MaxUnaryFileSizeBytes != nil {
		in, out := &in.MaxUnaryFileSizeBytes, &out.MaxUnaryFileSizeBytes
		*out = new(int64)
		**out = **in
	}
	if in.MaxDecodingMessageBytes != nil {
		in, out := &in.MaxDecodingMessageBytes, &out.MaxDecodingMessageBytes
		*out = new(int64)
		**out = **in
	}
	if in.MaxEncodingMessageBytes != nil {
		in, out := &in.MaxEncodingMessageBytes, &out.MaxEncodingMessageBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PseudoFSConfigSpec.
func (in *PseudoFSConfigSpec) DeepCopy() *PseudoFSConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PseudoFSConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PseudoFSList) DeepCopyInto(out *PseudoFSList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PseudoFS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PseudoFSList.
func (in *PseudoFSList) DeepCopy() *PseudoFSList {
	if in == nil {
		return nil
	}
	out := new(PseudoFSList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PseudoFSList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PseudoFSServiceSpec) DeepCopyInto(out *PseudoFSServiceSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PseudoFSServiceSpec.
func (in *PseudoFSServiceSpec) DeepCopy() *PseudoFSServiceSpec {
	if in == nil {
		return nil
	}
	out := new(PseudoFSServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PseudoFSSpec) DeepCopyInto(out *PseudoFSSpec) {
	*out = *in
	out.Image = in.Image
	in.Config.DeepCopyInto(&out.Config)
	in.Workload.DeepCopyInto(&out.Workload)
	in.Service.DeepCopyInto(&out.Service)
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PseudoFSSpec.
func (in *PseudoFSSpec) DeepCopy() *PseudoFSSpec {
	if in == nil {
		return nil
	}
	out := new(PseudoFSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PseudoFSStatus) DeepCopyInto(out *PseudoFSStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PseudoFSStatus.
func (in *PseudoFSStatus) DeepCopy() *PseudoFSStatus {
	if in == nil {
		return nil
	}
	out := new(PseudoFSStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingEpoch) DeepCopyInto(out *RoutingEpoch) {
	*out = *in
	in.Routing.DeepCopyInto(&out.Routing)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingEpoch.
func (in *RoutingEpoch) DeepCopy() *RoutingEpoch {
	if in == nil {
		return nil
	}
	out := new(RoutingEpoch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountSpec) DeepCopyInto(out *ServiceAccountSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountSpec.
func (in *ServiceAccountSpec) DeepCopy() *ServiceAccountSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardAssignment) DeepCopyInto(out *ShardAssignment) {
	*out = *in
	out.Owner = in.Owner
	out.Range = in.Range
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardAssignment.
func (in *ShardAssignment) DeepCopy() *ShardAssignment {
	if in == nil {
		return nil
	}
	out := new(ShardAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardMap) DeepCopyInto(out *ShardMap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardMap.
func (in *ShardMap) DeepCopy() *ShardMap {
	if in == nil {
		return nil
	}
	out := new(ShardMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShardMap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardMapList) DeepCopyInto(out *ShardMapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShardMap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardMapList.
func (in *ShardMapList) DeepCopy() *ShardMapList {
	if in == nil {
		return nil
	}
	out := new(ShardMapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShardMapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardMapSpec) DeepCopyInto(out *ShardMapSpec) {
	*out = *in
	if in.Epochs != nil {
		in, out := &in.Epochs, &out.Epochs
		*out = make([]RoutingEpoch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Assignments != nil {
		in, out := &in.Assignments, &out.Assignments
		*out = make([]ShardAssignment, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardMapSpec.
func (in *ShardMapSpec) DeepCopy() *ShardMapSpec {
	if in == nil {
		return nil
	}
	out := new(ShardMapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardOwner) DeepCopyInto(out *ShardOwner) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardOwner.
func (in *ShardOwner) DeepCopy() *ShardOwner {
	if in == nil {
		return nil
	}
	out := new(ShardOwner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardRange) DeepCopyInto(out *ShardRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardRange.
func (in *ShardRange) DeepCopy() *ShardRange {
	if in == nil {
		return nil
	}
	out := new(ShardRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardingSpec) DeepCopyInto(out *ShardingSpec) {
	*out = *in
	if in.IOConcurrencyLimit != nil {
		in, out := &in.IOConcurrencyLimit, &out.IOConcurrencyLimit
		*out = new(int32)
		**out = **in
	}
	if in.LeaseDurationSeconds != nil {
		in, out := &in.LeaseDurationSeconds, &out.LeaseDurationSeconds
		*out = new(int64)
		**out = **in
	}
	if in.RenewIntervalSeconds != nil {
		in, out := &in.RenewIntervalSeconds, &out.RenewIntervalSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardingSpec.
func (in *ShardingSpec) DeepCopy() *ShardingSpec {
	if in == nil {
		return nil
	}
	out := new(ShardingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	in.ObjectStore.DeepCopyInto(&out.ObjectStore)
	if in.BlockCache != nil {
		in, out := &in.BlockCache, &out.BlockCache
		*out = new(CacheSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MetaCache != nil {
		in, out := &in.MetaCache, &out.MetaCache
		*out = new(CacheSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Traces) DeepCopyInto(out *Traces) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Traces.
func (in *Traces) DeepCopy() *Traces {
	if in == nil {
		return nil
	}
	out := new(Traces)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Traces) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracesConfigSpec) DeepCopyInto(out *TracesConfigSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	if in.SegmentDurationSeconds != nil {
		in, out := &in.SegmentDurationSeconds, &out.SegmentDurationSeconds
		*out = new(int64)
		**out = **in
	}
	if in.RetentionSeconds != nil {
		in, out := &in.RetentionSeconds, &out.RetentionSeconds
		*out = new(int64)
		**out = **in
	}
	in.Page.DeepCopyInto(&out.Page)
	in.Write.DeepCopyInto(&out.Write)
	in.Sharding.DeepCopyInto(&out.Sharding)
	in.Request.DeepCopyInto(&out.Request)
	if in.CacheWarmer != nil {
		in, out := &in.CacheWarmer, &out.CacheWarmer
		*out = new(CacheWarmerSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Auth.DeepCopyInto(&out.Auth)
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracesConfigSpec.
func (in *TracesConfigSpec) DeepCopy() *TracesConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TracesConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracesList) DeepCopyInto(out *TracesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Traces, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracesList.
func (in *TracesList) DeepCopy() *TracesList {
	if in == nil {
		return nil
	}
	out := new(TracesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TracesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracesPageSpec) DeepCopyInto(out *TracesPageSpec) {
	*out = *in
	if in.TargetSizeBytes != nil {
		in, out := &in.TargetSizeBytes, &out.TargetSizeBytes
		*out = new(int64)
		**out = **in
	}
	if in.MaxSizeBytes != nil {
		in, out := &in.MaxSizeBytes, &out.MaxSizeBytes
		*out = new(int64)
		**out = **in
	}
	if in.MaxTraces != nil {
		in, out := &in.MaxTraces, &out.MaxTraces
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracesPageSpec.
func (in *TracesPageSpec) DeepCopy() *TracesPageSpec {
	if in == nil {
		return nil
	}
	out := new(TracesPageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracesRequestSpec) DeepCopyInto(out *TracesRequestSpec) {
	*out = *in
	if in.MaxRequestBytes != nil {
		in, out := &in.MaxRequestBytes, &out.MaxRequestBytes
		*out = new(int64)
		**out = **in
	}
	if in.MaxDecodedRequestBytes != nil {
		in, out := &in.MaxDecodedRequestBytes, &out.MaxDecodedRequestBytes
		*out = new(int64)
		**out = **in
	}
	if in.RequestConcurrency != nil {
		in, out := &in.RequestConcurrency, &out.RequestConcurrency
		*out = new(int32)
		**out = **in
	}
	if in.MaxCandidates != nil {
		in, out := &in.MaxCandidates, &out.MaxCandidates
		*out = new(int64)
		**out = **in
	}
	if in.MaxSpansPerTrace != nil {
		in, out := &in.MaxSpansPerTrace, &out.MaxSpansPerTrace
		*out = new(int64)
		**out = **in
	}
	if in.QueryConcurrency != nil {
		in, out := &in.QueryConcurrency, &out.QueryConcurrency
		*out = new(int32)
		**out = **in
	}
	if in.MaxQueryLimit != nil {
		in, out := &in.MaxQueryLimit, &out.MaxQueryLimit
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracesRequestSpec.
func (in *TracesRequestSpec) DeepCopy() *TracesRequestSpec {
	if in == nil {
		return nil
	}
	out := new(TracesRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracesSpec) DeepCopyInto(out *TracesSpec) {
	*out = *in
	out.Image = in.Image
	in.Config.DeepCopyInto(&out.Config)
	in.Writer.DeepCopyInto(&out.Writer)
	in.Reader.DeepCopyInto(&out.Reader)
	in.Service.DeepCopyInto(&out.Service)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracesSpec.
func (in *TracesSpec) DeepCopy() *TracesSpec {
	if in == nil {
		return nil
	}
	out := new(TracesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracesStatus) DeepCopyInto(out *TracesStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.WriterScalingStatus.DeepCopyInto(&out.WriterScalingStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracesStatus.
func (in *TracesStatus) DeepCopy() *TracesStatus {
	if in == nil {
		return nil
	}
	out := new(TracesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSpec) DeepCopyInto(out *VolumeSpec) {
	*out = *in
	if in.EmptyDir != nil {
		in, out := &in.EmptyDir, &out.EmptyDir
		*out = new(v1.EmptyDirVolumeSource)
		(*in).DeepCopyInto(*out)
	}
	if in.PersistentVolumeClaim != nil {
		in, out := &in.PersistentVolumeClaim, &out.PersistentVolumeClaim
		*out = new(v1.PersistentVolumeClaimSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSpec.
func (in *VolumeSpec) DeepCopy() *VolumeSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSpec) DeepCopyInto(out *WorkloadSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DataVolume != nil {
		in, out := &in.DataVolume, &out.DataVolume
		*out = new(VolumeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CacheVolume != nil {
		in, out := &in.CacheVolume, &out.CacheVolume
		*out = new(VolumeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PersistentVolumeClaimRetentionPolicy != nil {
		in, out := &in.PersistentVolumeClaimRetentionPolicy, &out.PersistentVolumeClaimRetentionPolicy
		*out = new(PersistentVolumeClaimRetentionPolicySpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSpec.
func (in *WorkloadSpec) DeepCopy() *WorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WriteSpec) DeepCopyInto(out *WriteSpec) {
	*out = *in
	if in.FlushIntervalSeconds != nil {
		in, out := &in.FlushIntervalSeconds, &out.FlushIntervalSeconds
		*out = new(int64)
		**out = **in
	}
	if in.BufferQueueCapacity != nil {
		in, out := &in.BufferQueueCapacity, &out.BufferQueueCapacity
		*out = new(int32)
		**out = **in
	}
	if in.BufferFlushIntervalMilliseconds != nil {
		in, out := &in.BufferFlushIntervalMilliseconds, &out.BufferFlushIntervalMilliseconds
		*out = new(int64)
		**out = **in
	}
	if in.BufferSizeThresholdBytes != nil {
		in, out := &in.BufferSizeThresholdBytes, &out.BufferSizeThresholdBytes
		*out = new(int64)
		**out = **in
	}
	if in.RemoteConcurrency != nil {
		in, out := &in.RemoteConcurrency, &out.RemoteConcurrency
		*out = new(int32)
		**out = **in
	}
	if in.RemoteRetries != nil {
		in, out := &in.RemoteRetries, &out.RemoteRetries
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WriteSpec.
func (in *WriteSpec) DeepCopy() *WriteSpec {
	if in == nil {
		return nil
	}
	out := new(WriteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WriterScalingStatus) DeepCopyInto(out *WriterScalingStatus) {
	*out = *in
	if in.ShardCount != nil {
		in, out := &in.ShardCount, &out.ShardCount
		*out = new(int32)
		**out = **in
	}
	if in.ShardGeneration != nil {
		in, out := &in.ShardGeneration, &out.ShardGeneration
		*out = new(int64)
		**out = **in
	}
	if in.RoutingEpochs != nil {
		in, out := &in.RoutingEpochs, &out.RoutingEpochs
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WriterScalingStatus.
func (in *WriterScalingStatus) DeepCopy() *WriterScalingStatus {
	if in == nil {
		return nil
	}
	out := new(WriterScalingStatus)
	in.DeepCopyInto(out)
	return out
}
