//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSObjectStoreSpec) DeepCopyInto(out *AWSObjectStoreSpec) {
	*out = *in
	if in.AccessKeyIDSecretRef != nil {
		in, out := &in.AccessKeyIDSecretRef, &out.AccessKeyIDSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretAccessKeySecretRef != nil {
		in, out := &in.SecretAccessKeySecretRef, &out.SecretAccessKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SessionTokenSecretRef != nil {
		in, out := &in.SessionTokenSecretRef, &out.SessionTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSObjectStoreSpec.
func (in *AWSObjectStoreSpec) DeepCopy() *AWSObjectStoreSpec {
	if in == nil {
		return nil
	}
	out := new(AWSObjectStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessSpec) DeepCopyInto(out *AccessSpec) {
	*out = *in
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = make([]BasicCredentialSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Write != nil {
		in, out := &in.Write, &out.Write
		*out = make([]BasicCredentialSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessSpec.
func (in *AccessSpec) DeepCopy() *AccessSpec {
	if in == nil {
		return nil
	}
	out := new(AccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
	in.Global.DeepCopyInto(&out.Global)
	if in.JWT != nil {
		in, out := &in.JWT, &out.JWT
		*out = new(JWTSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.InternalTokenSecretRef != nil {
		in, out := &in.InternalTokenSecretRef, &out.InternalTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSpec.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClientSecretAuthSpec) DeepCopyInto(out *AzureClientSecretAuthSpec) {
	*out = *in
	in.ClientSecretKeyRef.DeepCopyInto(&out.ClientSecretKeyRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClientSecretAuthSpec.
func (in *AzureClientSecretAuthSpec) DeepCopy() *AzureClientSecretAuthSpec {
	if in == nil {
		return nil
	}
	out := new(AzureClientSecretAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureObjectStoreSpec) DeepCopyInto(out *AzureObjectStoreSpec) {
	*out = *in
	if in.AccessKeySecretRef != nil {
		in, out := &in.AccessKeySecretRef, &out.AccessKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SASTokenSecretRef != nil {
		in, out := &in.SASTokenSecretRef, &out.SASTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.BearerTokenSecretRef != nil {
		in, out := &in.BearerTokenSecretRef, &out.BearerTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(AzureClientSecretAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadIdentity != nil {
		in, out := &in.WorkloadIdentity, &out.WorkloadIdentity
		*out = new(AzureWorkloadIdentityAuthSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureObjectStoreSpec.
func (in *AzureObjectStoreSpec) DeepCopy() *AzureObjectStoreSpec {
	if in == nil {
		return nil
	}
	out := new(AzureObjectStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureWorkloadIdentityAuthSpec) DeepCopyInto(out *AzureWorkloadIdentityAuthSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureWorkloadIdentityAuthSpec.
func (in *AzureWorkloadIdentityAuthSpec) DeepCopy() *AzureWorkloadIdentityAuthSpec {
	if in == nil {
		return nil
	}
	out := new(AzureWorkloadIdentityAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicCredentialSpec) DeepCopyInto(out *BasicCredentialSpec) {
	*out = *in
	in.Password.DeepCopyInto(&out.Password)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicCredentialSpec.
func (in *BasicCredentialSpec) DeepCopy() *BasicCredentialSpec {
	if in == nil {
		return nil
	}
	out := new(BasicCredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheSpec) DeepCopyInto(out *CacheSpec) {
	*out = *in
	if in.MemoryCapacity != nil {
		in, out := &in.MemoryCapacity, &out.MemoryCapacity
		*out = new(int64)
		**out = **in
	}
	if in.DiskCapacity != nil {
		in, out := &in.DiskCapacity, &out.DiskCapacity
		*out = new(int64)
		**out = **in
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(int64)
		**out = **in
	}
	if in.Shards != nil {
		in, out := &in.Shards, &out.Shards
		*out = new(int32)
		**out = **in
	}
	if in.Flushers != nil {
		in, out := &in.Flushers, &out.Flushers
		*out = new(int32)
		**out = **in
	}
	if in.BufferPoolSize != nil {
		in, out := &in.BufferPoolSize, &out.BufferPoolSize
		*out = new(int64)
		**out = **in
	}
	if in.SubmitQueueSizeThreshold != nil {
		in, out := &in.SubmitQueueSizeThreshold, &out.SubmitQueueSizeThreshold
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheSpec.
func (in *CacheSpec) DeepCopy() *CacheSpec {
	if in == nil {
		return nil
	}
	out := new(CacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataStoreReference) DeepCopyInto(out *DataStoreReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataStoreReference.
func (in *DataStoreReference) DeepCopy() *DataStoreReference {
	if in == nil {
		return nil
	}
	out := new(DataStoreReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPObjectStoreSpec) DeepCopyInto(out *GCPObjectStoreSpec) {
	*out = *in
	if in.ServiceAccountKeySecretRef != nil {
		in, out := &in.ServiceAccountKeySecretRef, &out.ServiceAccountKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.BearerTokenSecretRef != nil {
		in, out := &in.BearerTokenSecretRef, &out.BearerTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPObjectStoreSpec.
func (in *GCPObjectStoreSpec) DeepCopy() *GCPObjectStoreSpec {
	if in == nil {
		return nil
	}
	out := new(GCPObjectStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressMetadataSpec) DeepCopyInto(out *IngressMetadataSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressMetadataSpec.
func (in *IngressMetadataSpec) DeepCopy() *IngressMetadataSpec {
	if in == nil {
		return nil
	}
	out := new(IngressMetadataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressTLSSpec) DeepCopyInto(out *IngressTLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressTLSSpec.
func (in *IngressTLSSpec) DeepCopy() *IngressTLSSpec {
	if in == nil {
		return nil
	}
	out := new(IngressTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWKSSpec) DeepCopyInto(out *JWKSSpec) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWKSSpec.
func (in *JWKSSpec) DeepCopy() *JWKSSpec {
	if in == nil {
		return nil
	}
	out := new(JWKSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTSpec) DeepCopyInto(out *JWTSpec) {
	*out = *in
	in.JWKS.DeepCopyInto(&out.JWKS)
	if in.RefreshIntervalSeconds != nil {
		in, out := &in.RefreshIntervalSeconds, &out.RefreshIntervalSeconds
		*out = new(int64)
		**out = **in
	}
	if in.RequestTimeoutSeconds != nil {
		in, out := &in.RequestTimeoutSeconds, &out.RequestTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTSpec.
func (in *JWTSpec) DeepCopy() *JWTSpec {
	if in == nil {
		return nil
	}
	out := new(JWTSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Line) DeepCopyInto(out *Line) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Line.
func (in *Line) DeepCopy() *Line {
	if in == nil {
		return nil
	}
	out := new(Line)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Line) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineCacheSpec) DeepCopyInto(out *LineCacheSpec) {
	*out = *in
	if in.QueryEntries != nil {
		in, out := &in.QueryEntries, &out.QueryEntries
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineCacheSpec.
func (in *LineCacheSpec) DeepCopy() *LineCacheSpec {
	if in == nil {
		return nil
	}
	out := new(LineCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineConfigSpec) DeepCopyInto(out *LineConfigSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	if in.SegmentDurationSeconds != nil {
		in, out := &in.SegmentDurationSeconds, &out.SegmentDurationSeconds
		*out = new(int64)
		**out = **in
	}
	if in.RetentionSeconds != nil {
		in, out := &in.RetentionSeconds, &out.RetentionSeconds
		*out = new(int64)
		**out = **in
	}
	in.Page.DeepCopyInto(&out.Page)
	if in.VisibilityIntervalSeconds != nil {
		in, out := &in.VisibilityIntervalSeconds, &out.VisibilityIntervalSeconds
		*out = new(int64)
		**out = **in
	}
	in.Write.DeepCopyInto(&out.Write)
	in.Sharding.DeepCopyInto(&out.Sharding)
	in.Request.DeepCopyInto(&out.Request)
	in.Cache.DeepCopyInto(&out.Cache)
	in.Auth.DeepCopyInto(&out.Auth)
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineConfigSpec.
func (in *LineConfigSpec) DeepCopy() *LineConfigSpec {
	if in == nil {
		return nil
	}
	out := new(LineConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineList) DeepCopyInto(out *LineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Line, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineList.
func (in *LineList) DeepCopy() *LineList {
	if in == nil {
		return nil
	}
	out := new(LineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinePageSpec) DeepCopyInto(out *LinePageSpec) {
	*out = *in
	if in.TargetSizeBytes != nil {
		in, out := &in.TargetSizeBytes, &out.TargetSizeBytes
		*out = new(int64)
		**out = **in
	}
	if in.MaxRows != nil {
		in, out := &in.MaxRows, &out.MaxRows
		*out = new(int64)
		**out = **in
	}
	if in.MaxAgeSeconds != nil {
		in, out := &in.MaxAgeSeconds, &out.MaxAgeSeconds
		*out = new(int64)
		**out = **in
	}
	if in.RowsPerBlock != nil {
		in, out := &in.RowsPerBlock, &out.RowsPerBlock
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinePageSpec.
func (in *LinePageSpec) DeepCopy() *LinePageSpec {
	if in == nil {
		return nil
	}
	out := new(LinePageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineRequestSpec) DeepCopyInto(out *LineRequestSpec) {
	*out = *in
	if in.MaxRequestBytes != nil {
		in, out := &in.MaxRequestBytes, &out.MaxRequestBytes
		*out = new(int64)
		**out = **in
	}
	if in.MaxQueryEntries != nil {
		in, out := &in.MaxQueryEntries, &out.MaxQueryEntries
		*out = new(int64)
		**out = **in
	}
	if in.MaxQueryPages != nil {
		in, out := &in.MaxQueryPages, &out.MaxQueryPages
		*out = new(int64)
		**out = **in
	}
	if in.MaxStructuredMetadataFields != nil {
		in, out := &in.MaxStructuredMetadataFields, &out.MaxStructuredMetadataFields
		*out = new(int64)
		**out = **in
	}
	if in.QueryConcurrency != nil {
		in, out := &in.QueryConcurrency, &out.QueryConcurrency
		*out = new(int32)
		**out = **in
	}
	if in.MaxInFlightQueryBytes != nil {
		in, out := &in.MaxInFlightQueryBytes, &out.MaxInFlightQueryBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineRequestSpec.
func (in *LineRequestSpec) DeepCopy() *LineRequestSpec {
	if in == nil {
		return nil
	}
	out := new(LineRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineSpec) DeepCopyInto(out *LineSpec) {
	*out = *in
	out.Image = in.Image
	in.Config.DeepCopyInto(&out.Config)
	in.Writer.DeepCopyInto(&out.Writer)
	in.Reader.DeepCopyInto(&out.Reader)
	in.Service.DeepCopyInto(&out.Service)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineSpec.
func (in *LineSpec) DeepCopy() *LineSpec {
	if in == nil {
		return nil
	}
	out := new(LineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineStatus) DeepCopyInto(out *LineStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineStatus.
func (in *LineStatus) DeepCopy() *LineStatus {
	if in == nil {
		return nil
	}
	out := new(LineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Meter) DeepCopyInto(out *Meter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Meter.
func (in *Meter) DeepCopy() *Meter {
	if in == nil {
		return nil
	}
	out := new(Meter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Meter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterConfigSpec) DeepCopyInto(out *MeterConfigSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	if in.ReaderCacheCapacity != nil {
		in, out := &in.ReaderCacheCapacity, &out.ReaderCacheCapacity
		*out = new(int64)
		**out = **in
	}
	in.Write.DeepCopyInto(&out.Write)
	in.Sharding.DeepCopyInto(&out.Sharding)
	in.Auth.DeepCopyInto(&out.Auth)
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterConfigSpec.
func (in *MeterConfigSpec) DeepCopy() *MeterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(MeterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterList) DeepCopyInto(out *MeterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Meter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterList.
func (in *MeterList) DeepCopy() *MeterList {
	if in == nil {
		return nil
	}
	out := new(MeterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterSpec) DeepCopyInto(out *MeterSpec) {
	*out = *in
	out.Image = in.Image
	in.Config.DeepCopyInto(&out.Config)
	in.Writer.DeepCopyInto(&out.Writer)
	in.Reader.DeepCopyInto(&out.Reader)
	in.Service.DeepCopyInto(&out.Service)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterSpec.
func (in *MeterSpec) DeepCopy() *MeterSpec {
	if in == nil {
		return nil
	}
	out := new(MeterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterStatus) DeepCopyInto(out *MeterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterStatus.
func (in *MeterStatus) DeepCopy() *MeterStatus {
	if in == nil {
		return nil
	}
	out := new(MeterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceAuthentication) DeepCopyInto(out *NamespaceAuthentication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceAuthentication.
func (in *NamespaceAuthentication) DeepCopy() *NamespaceAuthentication {
	if in == nil {
		return nil
	}
	out := new(NamespaceAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceAuthentication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceAuthenticationList) DeepCopyInto(out *NamespaceAuthenticationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NamespaceAuthentication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceAuthenticationList.
func (in *NamespaceAuthenticationList) DeepCopy() *NamespaceAuthenticationList {
	if in == nil {
		return nil
	}
	out := new(NamespaceAuthenticationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceAuthenticationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceAuthenticationSpec) DeepCopyInto(out *NamespaceAuthenticationSpec) {
	*out = *in
	out.DataStoreRef = in.DataStoreRef
	in.SecretKeyRef.DeepCopyInto(&out.SecretKeyRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceAuthenticationSpec.
func (in *NamespaceAuthenticationSpec) DeepCopy() *NamespaceAuthenticationSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceAuthenticationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceAuthenticationStatus) DeepCopyInto(out *NamespaceAuthenticationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceAuthenticationStatus.
func (in *NamespaceAuthenticationStatus) DeepCopy() *NamespaceAuthenticationStatus {
	if in == nil {
		return nil
	}
	out := new(NamespaceAuthenticationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreSpec) DeepCopyInto(out *ObjectStoreSpec) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSObjectStoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureObjectStoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(GCPObjectStoreSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreSpec.
func (in *ObjectStoreSpec) DeepCopy() *ObjectStoreSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountSpec) DeepCopyInto(out *ServiceAccountSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountSpec.
func (in *ServiceAccountSpec) DeepCopy() *ServiceAccountSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardingSpec) DeepCopyInto(out *ShardingSpec) {
	*out = *in
	if in.VirtualShards != nil {
		in, out := &in.VirtualShards, &out.VirtualShards
		*out = new(int32)
		**out = **in
	}
	if in.LeaseDurationSeconds != nil {
		in, out := &in.LeaseDurationSeconds, &out.LeaseDurationSeconds
		*out = new(int64)
		**out = **in
	}
	if in.RenewIntervalSeconds != nil {
		in, out := &in.RenewIntervalSeconds, &out.RenewIntervalSeconds
		*out = new(int64)
		**out = **in
	}
	if in.WatchPollIntervalSeconds != nil {
		in, out := &in.WatchPollIntervalSeconds, &out.WatchPollIntervalSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardingSpec.
func (in *ShardingSpec) DeepCopy() *ShardingSpec {
	if in == nil {
		return nil
	}
	out := new(ShardingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	in.ObjectStore.DeepCopyInto(&out.ObjectStore)
	if in.BlockCache != nil {
		in, out := &in.BlockCache, &out.BlockCache
		*out = new(CacheSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MetaCache != nil {
		in, out := &in.MetaCache, &out.MetaCache
		*out = new(CacheSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSpec) DeepCopyInto(out *VolumeSpec) {
	*out = *in
	if in.EmptyDir != nil {
		in, out := &in.EmptyDir, &out.EmptyDir
		*out = new(v1.EmptyDirVolumeSource)
		(*in).DeepCopyInto(*out)
	}
	if in.PersistentVolumeClaim != nil {
		in, out := &in.PersistentVolumeClaim, &out.PersistentVolumeClaim
		*out = new(v1.PersistentVolumeClaimSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSpec.
func (in *VolumeSpec) DeepCopy() *VolumeSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSpec) DeepCopyInto(out *WorkloadSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DataVolume != nil {
		in, out := &in.DataVolume, &out.DataVolume
		*out = new(VolumeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CacheVolume != nil {
		in, out := &in.CacheVolume, &out.CacheVolume
		*out = new(VolumeSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSpec.
func (in *WorkloadSpec) DeepCopy() *WorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WriteSpec) DeepCopyInto(out *WriteSpec) {
	*out = *in
	if in.FlushIntervalSeconds != nil {
		in, out := &in.FlushIntervalSeconds, &out.FlushIntervalSeconds
		*out = new(int64)
		**out = **in
	}
	if in.RemoteConcurrency != nil {
		in, out := &in.RemoteConcurrency, &out.RemoteConcurrency
		*out = new(int32)
		**out = **in
	}
	if in.RemoteRetries != nil {
		in, out := &in.RemoteRetries, &out.RemoteRetries
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WriteSpec.
func (in *WriteSpec) DeepCopy() *WriteSpec {
	if in == nil {
		return nil
	}
	out := new(WriteSpec)
	in.DeepCopyInto(out)
	return out
}
