apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: traces-editor-role
rules:
- apiGroups: [telemetry.plural.sh]
  resources: [traces]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [telemetry.plural.sh]
  resources: [traces/status]
  verbs: [get]
