"""Markdown and JSON views over history entries; output depends only on entries."""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any

from .entry import SCHEMA_VERSION

GENERATED = (
    "<!-- Generated by `python -m harness.fuzz.history rebuild` from the JSON "
    "entries under history/. Do not edit by hand. -->"
)
RECENT_ROWS = 10
_ROLES = ("impl", "oracle", "shared")


def _ms(value: Any) -> str:
    return "-" if value is None else f"{value:.1f}"


def _ratio(value: Any) -> str:
    return "-" if value is None else f"{value:.2f}x"


def _num(value: Any, digits: int = 0) -> str:
    return "-" if value is None else f"{value:.{digits}f}"


def _pair(left: str, right: str) -> str:
    return f"{left} / {right}"


def _cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _row(cells: Iterable[Any]) -> str:
    return "| " + " | ".join(_cell(cell) for cell in cells) + " |"


def _duration(seconds: Any) -> str:
    if seconds is None:
        return "-"
    seconds = float(seconds)
    if seconds >= 3600 and seconds % 3600 == 0:
        return f"{seconds / 3600:g}h"
    if seconds >= 60 and seconds % 60 == 0:
        return f"{seconds / 60:g}m"
    return f"{seconds:g}s"


def _when(entry: dict[str, Any]) -> str:
    return entry["started_at"][:16].replace("T", " ") + "Z"


def _commit(entry: dict[str, Any]) -> str:
    git = entry.get("git") or {}
    text = f"`{git['short']}`" if git.get("short") else "-"
    return text + (" (dirty)" if git.get("dirty") else "")


def _status(entry: dict[str, Any]) -> str:
    results = entry["results"]
    if results["status"] == "passed":
        return "passed"
    return f"**FAILED** ({len(results['reasons'])})"


def _role(entry: dict[str, Any], role: str) -> dict[str, Any]:
    resources = entry["results"].get("resources") or {}
    return resources.get("roles", {}).get(role) or {}


def _cores(entry: dict[str, Any], role: str) -> Any:
    return (_role(entry, role).get("cpu_cores") or {}).get("mean")


def _memory(entry: dict[str, Any], role: str) -> Any:
    return (_role(entry, role).get("memory_mib") or {}).get("p95")


def _latency(entry: dict[str, Any], side: str, key: str) -> Any:
    return entry["results"]["latency"][f"{side}_ms"].get(key)


def _host(entry: dict[str, Any]) -> str:
    host = entry.get("host") or {}
    parts = [
        host.get("label"),
        " ".join(str(p) for p in (host.get("os"), host.get("arch")) if p) or None,
        host.get("cpu"),
        f"{host['cores']} cores" if host.get("cores") else None,
        f"{host['memory_gib']:g} GiB" if host.get("memory_gib") else None,
    ]
    return ", ".join(part for part in parts if part) or "-"


def _docker(entry: dict[str, Any]) -> str:
    docker = (entry.get("host") or {}).get("docker") or {}
    if not docker:
        return "-"
    parts = [
        docker.get("version"),
        docker.get("os"),
        f"{docker['cpus']} CPUs" if docker.get("cpus") else None,
        f"{docker['memory_gib']:g} GiB" if docker.get("memory_gib") else None,
    ]
    return ", ".join(str(part) for part in parts if part)


_COLUMNS = (
    ("started", "---"),
    ("commit", "---"),
    ("variant", "---"),
    ("status", "---"),
    ("budget", "---:"),
    ("cases", "---:"),
    ("mismatch", "---:"),
    ("non-match", "---:"),
    ("p50 ms impl / oracle", "---:"),
    ("p99 ms impl / oracle", "---:"),
    ("ratio p50", "---:"),
    ("CPU cores impl / oracle", "---:"),
    ("memory p95 MiB impl / oracle", "---:"),
    ("entry", "---"),
)


def history_header(with_product: bool = False) -> list[str]:
    columns = ((("product", "---"),) if with_product else ()) + _COLUMNS
    return [
        "| " + " | ".join(name for name, _ in columns) + " |",
        "| " + " | ".join(align for _, align in columns) + " |",
    ]


def history_row(entry: dict[str, Any], link: str, with_product: bool = False) -> str:
    results = entry["results"]
    return _row(
        (
            *((entry["product"],) if with_product else ()),
            _when(entry),
            _commit(entry),
            entry["variant"],
            _status(entry),
            _duration(entry["config"].get("duration_s")),
            results["cases"],
            results["outcomes"].get("mismatch", 0),
            results["non_match"],
            _pair(
                _ms(_latency(entry, "impl", "p50")),
                _ms(_latency(entry, "oracle", "p50")),
            ),
            _pair(
                _ms(_latency(entry, "impl", "p99")),
                _ms(_latency(entry, "oracle", "p99")),
            ),
            _ratio(results["latency"]["ratio"].get("p50")),
            _pair(_num(_cores(entry, "impl"), 2), _num(_cores(entry, "oracle"), 2)),
            _pair(_num(_memory(entry, "impl")), _num(_memory(entry, "oracle"))),
            f"[{entry['name']}]({link})",
        )
    )


def render_entry(entry: dict[str, Any]) -> str:
    results = entry["results"]
    config = entry["config"]
    git = entry.get("git") or {}
    lines = [
        f"# {entry['product']} fuzz benchmark, {_when(entry)} ({results['status']})",
        "",
        GENERATED,
        "",
        f"[{entry['product']} history](README.md) · [raw entry]({entry['name']}.json)",
        "",
        "| | |",
        "| --- | --- |",
        _row(("Product", f"{entry['product']} (`{entry['variant']}`)")),
        _row(("Started / finished", f"{entry['started_at']} / {entry['finished_at']}")),
        _row(
            (
                "Commit",
                f"{_commit(entry)} on `{git.get('branch') or '-'}`"
                + (f", commit `{git['commit']}`" if git.get("commit") else ""),
            )
        ),
        _row(("Host", _host(entry))),
        _row(("Docker", _docker(entry))),
        _row(
            (
                "Budget",
                f"{_duration(config.get('duration_s'))} (ran "
                f"{results['elapsed_s']}s), seed `{config.get('seed')}`, scale "
                f"{config.get('scale')}, window {_duration(config.get('window_s'))}, "
                f"stack `{config.get('stack')}`",
            )
        ),
        _row(
            (
                "Data",
                f"{results['rounds']} rounds ({results['invisible_rounds']} never "
                f"visible), {results['cases']} query cases, "
                f"{results['ingest']['batches']} write batches",
            )
        ),
    ]
    if entry.get("batch"):
        lines.append(_row(("Batch", f"`{entry['batch']}`")))
    if entry.get("ci"):
        ci = entry["ci"]
        lines.append(_row(("CI", f"{ci.get('workflow')} run {ci.get('run_id')}")))
    if results["reasons"]:
        lines += ["", "Failure reasons:", ""]
        lines += [f"- {reason}" for reason in results["reasons"]]
    if results["notes"]:
        lines += ["", "Notes:", ""]
        lines += [f"- {note}" for note in results["notes"]]
        if results.get("notes_truncated"):
            lines.append(f"- … {results['notes_truncated']} more")
    lines += ["", "## Correctness", "", "| outcome | cases |", "| --- | ---: |"]
    lines += [_row((name, count)) for name, count in results["outcomes"].items()]
    latency = results["latency"]
    lines += [
        "",
        "## Query latency",
        "",
        "Milliseconds over every case both sides answered. Ratio is the per-case "
        f"implementation / oracle latency: p50 {_ratio(latency['ratio'].get('p50'))}, "
        f"p90 {_ratio(latency['ratio'].get('p90'))}, "
        f"p99 {_ratio(latency['ratio'].get('p99'))}; "
        f"{latency['outliers']} latency outliers.",
        "",
        "| side | p50 | p90 | p99 | p99.9 | max |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for side, key in (("implementation", "impl_ms"), ("oracle", "oracle_ms")):
        lines.append(_row((side, *(_ms(v) for v in latency[key].values()))))
    ingest = results["ingest"]
    lines += [
        "",
        "## Ingest",
        "",
        f"{ingest['batches']} write batches, outcomes "
        + (
            ", ".join(f"{name} {count}" for name, count in ingest["outcomes"].items())
            or "-"
        )
        + ".",
        "",
        "| side | p50 | p90 | p99 | max |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for side, key in (("implementation", "impl_ms"), ("oracle", "oracle_ms")):
        lines.append(_row((side, *(_ms(v) for v in ingest[key].values()))))
    resources = results.get("resources")
    if resources and resources["roles"]:
        lines += [
            "",
            "## Resources",
            "",
            f"Container usage over {resources['elapsed_s']}s, sampled every "
            f"{resources['interval_s']}s. `shared` is object storage used by both "
            "sides.",
            "",
            "| role | services | CPU s | cores mean / p95 / max "
            "| memory MiB mean / p95 / max |",
            "| --- | --- | ---: | ---: | ---: |",
        ]
        for role, stats in resources["roles"].items():
            cores, memory = stats["cpu_cores"], stats["memory_mib"]
            lines.append(
                _row(
                    (
                        role,
                        ", ".join(stats["services"]),
                        _num(stats["cpu_seconds"], 1),
                        " / ".join(_num(v, 2) for v in cores.values()),
                        " / ".join(_num(v) for v in memory.values()),
                    )
                )
            )
    lines += [
        "",
        "## Query families",
        "",
        "| family | cases | non-match | impl p50 / p90 / p99 ms "
        "| oracle p50 / p90 / p99 ms | ratio p50 / p90 |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for family, stats in results["families"].items():
        lines.append(
            _row(
                (
                    family,
                    stats["cases"],
                    stats["non_match"],
                    " / ".join(_ms(v) for v in stats["impl_ms"].values()),
                    " / ".join(_ms(v) for v in stats["oracle_ms"].values()),
                    " / ".join(_ratio(v) for v in stats["ratio"].values()),
                )
            )
        )
    if entry.get("images"):
        lines += [
            "",
            "## Images",
            "",
            "| service | image | id |",
            "| --- | --- | --- |",
        ]
        for service, image in entry["images"].items():
            lines.append(_row((service, f"`{image['image']}`", f"`{image['id']}`")))
    if entry.get("environment"):
        lines += ["", "## Settings", ""]
        lines += [f"- `{name}={value}`" for name, value in entry["environment"].items()]
    return "\n".join(lines) + "\n"


def _newest_first(entries: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return sorted(entries, key=lambda e: (e["started_at"], e["name"]), reverse=True)


def render_product(product: str, entries: list[dict[str, Any]]) -> str:
    lines = [
        f"# {product} fuzz benchmark history",
        "",
        GENERATED,
        "",
        "[All products](../../README.md) · newest first. Rows with different "
        "variants (oracle, storage, config) are not directly comparable.",
        "",
    ]
    if not entries:
        return "\n".join([*lines, "No runs recorded yet."]) + "\n"
    lines += history_header()
    lines += [history_row(e, f"{e['name']}.md") for e in _newest_first(entries)]
    return "\n".join(lines) + "\n"


def latest(entries: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Newest entry per (product, variant), ordered by product then variant."""
    chosen: dict[tuple[str, str], dict[str, Any]] = {}
    for entry in _newest_first(entries):
        chosen.setdefault((entry["product"], entry["variant"]), entry)
    return [chosen[key] for key in sorted(chosen)]


def render_index(products: list[str], entries: list[dict[str, Any]]) -> str:
    lines = [
        "# Differential fuzz benchmark history",
        "",
        GENERATED,
        "",
        "Each run fuzzes one product against its reference system (logs vs "
        "Loki, metrics vs Prometheus or Mimir, traces vs Tempo) on a local "
        "Docker stack, then records correctness outcomes, query and ingest "
        "latency, and container CPU and memory. See the "
        "[benchmark guide](../README.md) for what the numbers mean and how to "
        "add a run. Machine-readable data: [index.json](index.json).",
        "",
        "## Latest results",
        "",
    ]
    if entries:
        lines.append(
            "Newest run per product and variant. Latency is per answered query; "
            "CPU is mean cores and memory is p95 working set over the run."
        )
        lines += ["", *history_header(with_product=True)]
        for entry in latest(entries):
            link = f"history/{entry['product']}/{entry['name']}.md"
            lines.append(history_row(entry, link, with_product=True))
    else:
        lines.append("No runs recorded yet.")
    for product in products:
        runs = _newest_first([e for e in entries if e["product"] == product])
        lines += [
            "",
            f"## {product}",
            "",
            f"[Full history](history/{product}/README.md) ({len(runs)} "
            f"run{'s' if len(runs) != 1 else ''}).",
        ]
        if runs:
            lines += ["", *history_header()]
            lines += [
                history_row(e, f"history/{product}/{e['name']}.md")
                for e in runs[:RECENT_ROWS]
            ]
    return "\n".join(lines) + "\n"


def _index_record(entry: dict[str, Any]) -> dict[str, Any]:
    results = entry["results"]
    git = entry.get("git") or {}
    host = entry.get("host") or {}
    docker = host.get("docker") or {}
    product, name = entry["product"], entry["name"]
    return {
        "name": name,
        "product": product,
        "variant": entry["variant"],
        "batch": entry.get("batch"),
        "started_at": entry["started_at"],
        "finished_at": entry["finished_at"],
        "json": f"history/{product}/{name}.json",
        "markdown": f"history/{product}/{name}.md",
        "git": {key: git.get(key) for key in ("commit", "short", "branch", "dirty")},
        "host": {
            "label": host.get("label"),
            "cpu": host.get("cpu"),
            "cores": host.get("cores"),
            "docker_cpus": docker.get("cpus"),
            "docker_memory_gib": docker.get("memory_gib"),
        },
        "config": {
            key: entry["config"].get(key) for key in ("duration_s", "seed", "scale")
        },
        "settings": entry["settings"],
        "status": results["status"],
        "reasons": len(results["reasons"]),
        "rounds": results["rounds"],
        "cases": results["cases"],
        "mismatch": results["outcomes"].get("mismatch", 0),
        "non_match": results["non_match"],
        "outcomes": results["outcomes"],
        "latency": {
            "impl_ms": {k: _latency(entry, "impl", k) for k in ("p50", "p90", "p99")},
            "oracle_ms": {
                k: _latency(entry, "oracle", k) for k in ("p50", "p90", "p99")
            },
            "ratio_p50": results["latency"]["ratio"].get("p50"),
        },
        "resources": {
            role: {
                "cpu_cores_mean": _cores(entry, role),
                "memory_mib_p95": _memory(entry, role),
            }
            for role in _ROLES
            if _role(entry, role)
        },
    }


def index_json(products: list[str], entries: list[dict[str, Any]]) -> dict[str, Any]:
    ordered = sorted(entries, key=lambda e: (e["product"], e["started_at"], e["name"]))
    newest = {e["product"]: e["name"] for e in ordered}
    return {
        "schema_version": SCHEMA_VERSION,
        "products": {
            product: {
                "runs": sum(1 for e in ordered if e["product"] == product),
                "latest": newest.get(product),
                "readme": f"history/{product}/README.md",
            }
            for product in products
        },
        "entries": [_index_record(entry) for entry in ordered],
    }
