apiVersion: v2
name: meter
description: Production-oriented Helm chart for Meter
appVersion: 0.1.1
version: 0.1.4
sources:
  - https://github.com/pluralsh/telemetry
type: application
kubeVersion: '>=1.25.0-0'
keywords:
  - telemetry
  - prometheus
  - metrics
home: https://github.com/pluralsh/telemetry
