[package]
name = "proto"
description = "Internal protobuf contracts for Telemetry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[lints]
workspace = true

[dependencies]
prost.workspace = true
tonic.workspace = true

[build-dependencies]
prost-build.workspace = true
protoc-bin-vendored.workspace = true
tonic-build.workspace = true
