[package]
name = "telemetry-scalability"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
anyhow = "1.0.104"
base64 = "0.23.1"
clap = { version = "4.6.7", features = ["derive"] }
hdrhistogram = "7.6.0"
prost = "0.14.4"
reqwest = { version = "0.13.5", default-features = false, features = ["rustls", "http2"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
snap = "1.1.2"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "time", "signal"] }
uuid = { version = "1.26.1", features = ["v4"] }
