apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pseudofs.fullname" . }}
  labels:
    {{- include "pseudofs.labels" . | nindent 4 }}
data:
  pseudofs.yaml: |
    listener: 0.0.0.0:{{ .Values.service.port }}
    filesystem:
      {{- toYaml .Values.config.filesystem | nindent 6 }}
    max_unary_file_size_bytes: {{ printf "%.0f" .Values.config.maxUnaryFileSizeBytes }}
    max_decoding_message_bytes: {{ printf "%.0f" .Values.config.maxDecodingMessageBytes }}
    max_encoding_message_bytes: {{ printf "%.0f" .Values.config.maxEncodingMessageBytes }}
